Time Tracker Packaging Org/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Time_Spent__c</fullName>
        <formula>TEXT( FLOOR(Tracked_Duration__c/3600)) + 

&apos;:&apos; + 

IF( 
FLOOR(MOD(Tracked_Duration__c,3600)/60) &lt; 10, 
&apos;0&apos; + TEXT(FLOOR(MOD(Tracked_Duration__c,3600)/60)), 
TEXT(FLOOR(MOD(Tracked_Duration__c,3600)/60))) + &apos;:&apos; + 

IF( 
MOD(MOD(Tracked_Duration__c,3600),60) &lt; 10, 
&apos;0&apos;+ TEXT(MOD(MOD(Tracked_Duration__c,3600),60)), 
TEXT(MOD(MOD(Tracked_Duration__c,3600),60)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Time Spent (HH:MM:SS)</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

Time Tracker Packaging Org/src/objects/Time_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Time_Spent__c</fullName>
        <defaultValue>&apos;00:00:00&apos;</defaultValue>
        <label>Time Spent (HH:MM:SS)</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timesheet_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Entry</label>
        <referenceTo>Timesheet_Entry__c</referenceTo>
        <relationshipLabel>Time Trackers</relationshipLabel>
        <relationshipName>Time_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Timesheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet</label>
        <referenceTo>Timesheet__c</referenceTo>
        <relationshipLabel>Time Trackers</relationshipLabel>
        <relationshipName>Time_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Tracker</label>
    <nameField>
        <displayFormat>TT-{000}</displayFormat>
        <label>Time Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Trackers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Time Tracker Packaging Org/src/objects/Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Time_Spent__c</fullName>
        <formula>TEXT( FLOOR(Total_Seconds__c/3600)) + 

&apos;:&apos; + 

IF( 
FLOOR(MOD(Total_Seconds__c,3600)/60) &lt; 10, 
&apos;0&apos; + TEXT(FLOOR(MOD(Total_Seconds__c,3600)/60)), 
TEXT(FLOOR(MOD(Total_Seconds__c,3600)/60))) + &apos;:&apos; + 

IF( 
MOD(MOD(Total_Seconds__c,3600),60) &lt; 10, 
&apos;0&apos;+ TEXT(MOD(MOD(Total_Seconds__c,3600),60)), 
TEXT(MOD(MOD(Total_Seconds__c,3600),60)))</formula>
        <label>Total Time Spent</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Timesheet_Identifier__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Unique Timesheet Identifier</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <label>Timesheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Timesheet_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Time_Spent__c</fullName>
        <defaultValue>&apos;00:00:00&apos;</defaultValue>
        <label>Time Spent (HH:MM:SS)</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timesheet__c</fullName>
        <label>Timesheet</label>
        <referenceTo>Timesheet__c</referenceTo>
        <relationshipLabel>Timesheet Entries</relationshipLabel>
        <relationshipName>Timesheet_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Timesheet Entry</label>
    <nameField>
        <displayFormat>TE-{0}</displayFormat>
        <label>Timesheet Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TimeTracker_StagingLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Name__c</fullName>
        <label>Activity Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>TimeTracker Staging Line Item</label>
    <nameField>
        <displayFormat>TSLI-{00000000}</displayFormat>
        <label>Time Tracker Staging Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TimeTracker Staging Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TimeTrackerConfigSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Code1__c</fullName>
        <description>Manual- Case or Account Link
Strategy- Implementation class Name</description>
        <label>Code 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Text1__c</fullName>
        <description>Manual- Activity
Strategy- Activity</description>
        <label>Text 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text3__c</fullName>
        <label>Text 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <externalId>true</externalId>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Time Tracker Config Settings</label>
</CustomObject>

Time Tracker Packaging Org/src/classes/TimeTrackerStagingAfterTSLcokTest.cls
@isTest
private class TimeTrackerStagingAfterTSLcokTest
{
	private static final String STANDARD_PROFILE_NAME = 'Standard User';
  	static List<Timesheet__c> listTimesheets;
	private static Datetime now = System.now();

	private static void init() {
		// method to install only new TimeTrackerConfigSettings records
		TimeTrackerTestHelper.insertRecordsFromStaticResource(TimeTrackerUtility.getNamespace()
		+ 'TimeTrackerConfigSettings__c',
		'TimeTrackerConfigSettings_Records');

		TimeTrackerConfigSettings__c setting = new TimeTrackerConfigSettings__c();
		setting.Name = 'Strategy_SnapEngage Chat';
		setting.Type__c = 'Strategy';
		setting.Text1__c = 'SnapEngage Chat';
		setting.Code1__c = 'GenericImpl';
		setting.Text3__c = 'Customer Chat';
		setting.IsActive__c = true;
		insert setting;
		System.assertNotEquals(0, TimeTrackerConfigSettings__c.getAll().values().size());

		Database.SaveResult sr = null;
		User stdUsr = TimeTrackerTestHelper.createUser(STANDARD_PROFILE_NAME);
        
		system.runAs(stdUsr) {
			//Test.startTest();
			Account acct = new Account(Name='Test Account');
			//insert the Account record
			sr = Database.Insert(acct, true);
			// ensure the Case record has an Id
			system.assertNotEquals(null, sr.getId());
			String acctid = sr.getId();

			//create a Case record
			Case newCase = new Case(OwnerId = stdUsr.Id);
			newCase.AccountId = acctid;

			//insert the Case record
			sr = Database.Insert(newCase, true);
			// ensure the Case record has an Id
			system.assertNotEquals(null, sr.getId());
			String sObjectId = sr.getId();

			// all information supplied
			String isSuccessful1 = TimeTrackerController.doCreateTimesheetEntry('00:01:00', '60',
			DateTime.now().format(),	TimeTrackerConstants.GENERAL_OTHER,
			null, null, 'TrackerComment');
			system.assertEquals('true', isSuccessful1);

			/*String isSuccessful2 = TimeTrackerController.doCreateTimesheetEntry('00:02:00', '2',
			DateTime.now().addDays(16).format(),	TimeTrackerConstants.CASE_REVIEW_STR,
			sObjectId, '2', 'TrackerComment');
			system.assertEquals('true', isSuccessful2);

			String isSuccessful3 = TimeTrackerController.doCreateTimesheetEntry('00:03:00', '3',
			DateTime.now().addDays(24).format(),	TimeTrackerConstants.CASE_REVIEW_STR,
			sObjectId, '3', 'TrackerComment');
			system.assertEquals('true', isSuccessful3);

			String isSuccessful4 = TimeTrackerController.doCreateTimesheetEntry('00:04:00', '4',
			DateTime.now().addDays(32).format(),	TimeTrackerConstants.CASE_REVIEW_STR,
			sObjectId, '4', 'TrackerComment');
			system.assertEquals('true', isSuccessful4);

			String isSuccessful5 = TimeTrackerController.doCreateTimesheetEntry('00:05:00', '5',
			DateTime.now().addDays(40).format(),	TimeTrackerConstants.CASE_REVIEW_STR,
			sObjectId, '5', 'TrackerComment');
			system.assertEquals('true', isSuccessful5);*/

			//Test.stopTest();
		}
	}

	private static void insertChats(){
		List<TimeTracker_StagingLineItem__c> stgRecList = new List<TimeTracker_StagingLineItem__c>();

		TimeTracker_StagingLineItem__c stgRec1 = new TimeTracker_StagingLineItem__c();
		stgRec1.Activity_Name__c = 'SnapEngage Chat';
		stgRec1.Start_Date__c = now.addMinutes(2);
		stgRec1.End_Date__c= now.addMinutes(17);
		stgRecList.add(stgRec1);

		/*TimeTracker_StagingLineItem__c stgRec2 = new TimeTracker_StagingLineItem__c();
		stgRec2.Activity_Name__c = 'Chat1';
		stgRec2.Start_Date__c = now.addDays(16).addMinutes(2);
		stgRec2.End_Date__c= now.addDays(16).addMinutes(17);
		stgRecList.add(stgRec2);

		TimeTracker_StagingLineItem__c stgRec3 = new TimeTracker_StagingLineItem__c();
		stgRec3.Activity_Name__c = 'Chat1';
		stgRec3.Start_Date__c = now.addDays(24).addMinutes(2);
		stgRec3.End_Date__c= now.addDays(24).addMinutes(17);
		stgRecList.add(stgRec3);

		TimeTracker_StagingLineItem__c stgRec4 = new TimeTracker_StagingLineItem__c();
		stgRec4.Activity_Name__c = 'Chat1';
		stgRec4.Start_Date__c = now.addDays(32).addMinutes(2);
		stgRec4.End_Date__c= now.addDays(32).addMinutes(17);
		stgRecList.add(stgRec4);

		TimeTracker_StagingLineItem__c stgRec5 = new TimeTracker_StagingLineItem__c();
		stgRec5.Activity_Name__c = 'Chat1';
		stgRec5.Start_Date__c = now.addDays(40).addMinutes(2);
		stgRec5.End_Date__c= now.addDays(40).addMinutes(17);
		stgRecList.add(stgRec5);*/

		Insert stgRecList;
	}
	

	@isTest
	static void timesheetSubmitTest() {
		init();
		listTimesheets = [SELECT Id, Name, Status__c, Comment__c,OwnerId,Total_Time_Spent__c,Unique_Timesheet_Identifier__c FROM Timesheet__c];
        
        User stdUsr = [SELECT Id, ManagerId FROM USER WHERE Alias = 'testUsr'];
        User stdMgr = TimeTrackerTestHelper.createUser();

		stdUsr.ManagerId = stdMgr.Id;
        
        update stdUsr;
		System.assertEquals(1, listTimesheets.size());
		//System.debug(listTimesheets);
        
        List<Id> tsIds = new List<Id>();
        System.runAs(stdUsr) {
            for(Timesheet__c ts : listTimesheets) {
                Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
                req.setComments('Submitting request for approval.');
                req.setObjectId(ts.id);
        
                // Submit on behalf of a specific submitter
                req.setSubmitterId(ts.OwnerId);
        
                // Submit the record to specific process and skip the criteria evaluation
                req.setProcessDefinitionNameOrId('Timesheet_Approval_Process');
                req.setSkipEntryCriteria(true);
        
                // Submit the approval request for the account
                //System.debug('request : '+req);
                Approval.ProcessResult result = Approval.process(req);
        
                // Verify the result
                System.assert(result.isSuccess());
        
                System.assertEquals(
                    'Pending', result.getInstanceStatus(),
                    'Instance Status'+result.getInstanceStatus()
                );
                tsIds.add(ts.Id);
            }
			insertChats();
        }
        //System.debug('listTimesheets : '+listTimesheets);
        System.assertEquals('0:01:00', listTimesheets[0].Total_Time_Spent__c);

        //Assert one Staging-records are present before Batch
		Integer existingStagingRecordsCount = [SELECT COUNT() FROM TimeTracker_StagingLineItem__c];
		System.assertEquals(1,existingStagingRecordsCount);

		//Assert one Time-tracker records are present before Batch
		List<Time_Tracker__c> ttAlreadyPresent = [SELECT Action__c, Timesheet__c, Timesheet_Entry__c,Time_Spent__c FROM Time_Tracker__c];
		//System.debug('ttAlreadyPresent : '+ttAlreadyPresent);
		System.assertEquals(1, ttAlreadyPresent.size());

		Test.startTest();
		TimeTrackerStagingLineItem processStagingRecords = new TimeTrackerStagingLineItem();
		Database.executeBatch(processStagingRecords);
		Test.stopTest();
		//Assert Time-tracker records are created after Batch
		List<Time_Tracker__c> ttInserted = [SELECT Action__c, Timesheet__c, Timesheet_Entry__c,Time_Spent__c FROM Time_Tracker__c];
		//System.debug('ttInserted : '+ttInserted);
		System.assertEquals(2, ttInserted.size());

		//Assert Timesheet will roll-up staging records to timesheet even after ts locked
		listTimesheets = [SELECT Id, Name, Status__c, Comment__c,OwnerId,Total_Time_Spent__c,Unique_Timesheet_Identifier__c FROM Timesheet__c];
		//System.debug('listTimesheets :'+listTimesheets);
		System.assertEquals('0:16:00', listTimesheets[0].Total_Time_Spent__c);

		//Assert Staging-records are deleted after Batch
		Integer stagingRecordsCountAfterBatch = [SELECT COUNT() FROM TimeTracker_StagingLineItem__c];
		System.assertEquals(0,stagingRecordsCountAfterBatch);
	}
}