Time Tracker Packaging Org/src/objects/Time_Tracker__c.object
<CustomObject>
    <label>Time Tracker</label>
    <nameField>
        <displayFormat>TT-{000}</displayFormat>
        <label>Time Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Trackers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TimeTracker_StagingLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Name__c</fullName>
        <label>Activity Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>TimeTracker Staging Line Item</label>
    <nameField>
        <displayFormat>TSLI-{00000000}</displayFormat>
        <label>Time Tracker Staging Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TimeTracker Staging Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Time Tracker Packaging Org/src/classes/TimeTrackerStagingLineItemTest.cls
@isTest(SeeAllData=false)
private class TimeTrackerStagingLineItemTest {

private static Datetime now = System.now();

	private static void insertChat1_S1(){
		TimeTracker_StagingLineItem__c stgRec = new TimeTracker_StagingLineItem__c();
		stgRec.Activity_Name__c = 'Chat1';
		stgRec.Start_Date__c = now.addMinutes(2);
		stgRec.End_Date__c= now.addMinutes(17);
		insert stgRec;
	}
	private static void insertChat2_S1(){
		TimeTracker_StagingLineItem__c stgRec = new TimeTracker_StagingLineItem__c();
		stgRec.Activity_Name__c = 'Chat2';
		stgRec.Start_Date__c = now.addMinutes(3);
		stgRec.End_Date__c= now.addMinutes(5);
		insert stgRec;
	}

	@isTest static void Test_TimeTrackerStagingLineItemTime_Batch(){
		insertChat1_S1();
		insertChat2_S1();

		//Assert Staging-records are present before Batch
		Integer existingStagingRecordsCount = [SELECT COUNT() FROM TimeTracker_StagingLineItem__c];
		System.assertEquals(2,existingStagingRecordsCount);

		//Assert No Time-tracker records are present before Batch
		Integer ttAlreadyPresent = [SELECT COUNT() FROM Time_Tracker__c];
		System.assertEquals(0, ttAlreadyPresent);

		Test.startTest();
			TimeTrackerStagingLineItem processStagingRecords = new TimeTrackerStagingLineItem();
			Database.executeBatch(processStagingRecords);
		Test.stopTest();

		//Assert Time-tracker records are created after Batch
		Integer ttInserted = [SELECT COUNT() FROM Time_Tracker__c];
		System.assertEquals(2, ttInserted);

		//Assert Staging-records are deleted after Batch
		Integer stagingRecordsCountAfterBatch = [SELECT COUNT() FROM TimeTracker_StagingLineItem__c];
		System.assertEquals(0,stagingRecordsCountAfterBatch);		
	}
}