Time Tracker Packaging Org/src/objects/Time_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <label>Activity Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Activity_Time__c</fullName>
        <externalId>true</externalId>
        <label>Activity Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DocumentId__c</fullName>
        <externalId>true</externalId>
        <label>Document Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Tracked Duration</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opening_Action__c</fullName>
        <label>Opening Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Change Status</fullName>
                </value>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
                <value>
                    <fullName>Edit</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Escalate to L3</fullName>
                </value>
                <value>
                    <fullName>File</fullName>
                </value>
                <value>
                    <fullName>File Upload</fullName>
                </value>
                <value>
                    <fullName>Log a Call</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>New Event</fullName>
                </value>
                <value>
                    <fullName>Post Case Comment</fullName>
                </value>
                <value>
                    <fullName>Start Chat</fullName>
                </value>
                <value>
                    <fullName>Update Case</fullName>
                </value>
                <value>
                    <fullName>Case Comment Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opening_Activity_Time__c</fullName>
        <externalId>true</externalId>
        <label>Opening Activity Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>Console Toolkit</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Time Tracker</label>
    <nameField>
        <displayFormat>TT-{000}</displayFormat>
        <label>Time Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Trackers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TimeTrackerConfigSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Code1__c</fullName>
        <description>Manual- Case or Account Link
Strategy- Implementation class Name</description>
        <label>Code 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flag1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Flag 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Flag 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Text1__c</fullName>
        <description>Manual- Activity
Strategy- Activity</description>
        <label>Text 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text2__c</fullName>
        <label>Text 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text3__c</fullName>
        <label>Text 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text5__c</fullName>
        <label>Text 5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <externalId>true</externalId>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Time Tracker Config Settings</label>
</CustomObject>

Time Tracker Packaging Org/src/classes/TimeTrackerComponentControllerTest.cls
/**
    @ Purpose : Tests the functionality of the controller --> TimeTrackerComponentControlller.
*/

@isTest
public class TimeTrackerComponentControllerTest {
    
    /*
        @ Purpose : Inserts the data/records requiered for testing.
    */
    @TestSetup static void insertTestData() {
        
        integer intNoOfRecords = 0;
        List<TimeTrackerConfigSettings__c> listOfConfigSettings = new List<TimeTrackerConfigSettings__c>
                                                                  {
                                                                   new TimeTrackerConfigSettings__c
                                                                   (
                                                                    Name = 'STRATEGY_NEW_CASE', Type__c = 'Strategy',
                                                                    Code1__c = 'GenericTimeTrackerImpl',
                                                                    Text1__c = 'New Case', Text2__c = 'Case Work', 
                                                                    Text3__c = 'Case Documentation',
                                                                    IsActive__c = TRUE, Flag1__c = TRUE, Flag2__c = TRUE
                                                                   ),
                                                                   new TimeTrackerConfigSettings__c
                                                                   (
                                                                    Name = 'STRATEGY_CASE_REVIEW', Type__c  = 'Strategy',
                                                                    Code1__c = 'GenericExcludeImpl',
                                                                    Text1__c = 'Case Review', Text2__c = 'Case Work',
                                                                    Text3__c = 'Case Documentation',
                                                                    Text5__c = 'New Case; Edit Case;',
                                                                    IsActive__c = TRUE, Flag1__c = TRUE, Flag2__c = TRUE
                                                                   )
                                                                  };
        intNoOfRecords = listOfConfigSettings.size();
        insert listOfConfigSettings;
        System.assertEquals( intNoOfRecords, [ SELECT COUNT() FROM TimeTrackerConfigSettings__c WHERE Type__c = 'Strategy' ] );
        
        listOfConfigSettings = new List<TimeTrackerConfigSettings__c>
                              {
                               new TimeTrackerConfigSettings__c
                               (
                                Name = 'MISCELLANEOUS_JS_ConsoleError', Type__c = 'Miscellaneous',
                                Code1__c = 'background: #970e02;color:#FFF;padding:5px;border-radius: 5px;line-height: 20px;',
                                IsActive__c = TRUE
                               ),
                               new TimeTrackerConfigSettings__c
                               (
                                Name = 'MISCELLANEOUS_JS_ConsoleInfo', Type__c  = 'Miscellaneous',
                                Code1__c = 'background: #3F51B5;color:#FFF;padding:5px;border-radius: 5px;line-height: 20px;',
                                IsActive__c = TRUE
                               ),
                               new TimeTrackerConfigSettings__c
                               (
                                Name = 'MISCELLANEOUS_JS_ConsoleLog', Type__c   = 'Miscellaneous',
                                Code1__c = 'background: #4ab471;color:#FFF;padding:5px;border-radius: 5px;line-height: 20px;',
                                IsActive__c = TRUE
                               ),
                               new TimeTrackerConfigSettings__c
                               (
                                Name = 'MISCELLANEOUS_JS_ConsoleSF', Type__c    = 'Miscellaneous',
                                Code1__c = 'background: #fcad02;color:#FFF;padding:5px;border-radius: 5px;line-height: 20px;',
                                IsActive__c = TRUE
                               )
                              };
        intNoOfRecords = listOfConfigSettings.size();
        insert listOfConfigSettings;
        System.assertEquals( intNoOfRecords, [ SELECT COUNT() FROM TimeTrackerConfigSettings__c WHERE Type__c = 'Miscellaneous' ] );
    }
    
    /*
        @ Purpose : Tests the functionality of getting object details and custom settings.
    */
    public static TestMethod void testGetObjectDetailsAndCustomSettings() {

        String strJsonSettings;
        TimeTrackerComponentWrapper wrapper;
        TimeTrackerComponentWrapper.ObjectWrapper objWrapper;

        Test.startTest();       
		
        // Covers code for instances declared.
        wrapper = new TimeTrackerComponentWrapper();
        objWrapper = new TimeTrackerComponentWrapper.ObjectWrapper();
		        
        // Tests with valid data.
        strJsonSettings = TimeTrackerComponentController.getObjectDetailsAndCustomSettings();
        wrapper = ( TimeTrackerComponentWrapper ) JSON.deserialize( strJsonSettings, TimeTrackerComponentWrapper.class );
        
        System.assertNotEquals( 0, wrapper.listOfStrategySettings.size() );
        System.assertNotEquals( 0, wrapper.listOfMiscellaneousSettings.size() );
        System.assertNotEquals( 0, wrapper.listOfObjectWrappers.size() );
		
        Test.stopTest();

        System.assertEquals( TRUE, wrapper.isSucceeded );
    }
    
    /*
        @ Purpose : Tests the functionality of inserting time tracker record.
    */
    public static TestMethod void testInsertTimeTracker() {

        String strJsonTimeTracker, strDocumentId;
        TimeTrackerComponentWrapper wrapper;
        Time_Tracker__c ttRecord;
        DateTime dt = DateTime.now();

        Test.startTest();       

        // Tests with no record.
        strJsonTimeTracker = TimeTrackerComponentController.insertTimeTracker( NULL );
        wrapper = ( TimeTrackerComponentWrapper ) JSON.deserialize( strJsonTimeTracker, TimeTrackerComponentWrapper.class );
        System.assertEquals( FALSE, wrapper.isSucceeded );
        
        // Tests with 'null' record.
        strJsonTimeTracker = TimeTrackerComponentController.insertTimeTracker( JSON.serialize( ttRecord ) );
        wrapper = ( TimeTrackerComponentWrapper ) JSON.deserialize( strJsonTimeTracker, TimeTrackerComponentWrapper.class );
        System.assertEquals( FALSE, wrapper.isSucceeded );
        
        // Tests with empty record.
        ttRecord = new Time_Tracker__c();
        strJsonTimeTracker = TimeTrackerComponentController.insertTimeTracker( JSON.serialize( ttRecord ) );
        wrapper = ( TimeTrackerComponentWrapper ) JSON.deserialize( strJsonTimeTracker, TimeTrackerComponentWrapper.class );
        System.assertEquals( TRUE, wrapper.isSucceeded );
        
        // Tests with opening record
        strDocumentId = '8659b5b2-4948-4ce1-957b-ad5083bd2ad8';
        ttRecord = new Time_Tracker__c
                   (
                    Action__c = 'New Case',
                    Activity_Date__c = dt,
                    Activity_Time__c = dt.getTime(),
                    DocumentId__c = strDocumentId,
                    Source__c = 'Lightning Component'
                   );
        strJsonTimeTracker = TimeTrackerComponentController.insertTimeTracker( JSON.serialize( ttRecord ) );
        wrapper = ( TimeTrackerComponentWrapper ) JSON.deserialize( strJsonTimeTracker, TimeTrackerComponentWrapper.class );
        System.assertEquals( TRUE, wrapper.isSucceeded );
        
        // Tests with closing record
        dt.addSeconds( 60 );
        ttRecord = new Time_Tracker__c
                   (
                    Action__c = 'Case Save',
                    Activity_Date__c = dt,
                    Activity_Time__c = dt.getTime(),
                    Opening_Activity_Time__c = wrapper.ttRecord.Activity_Time__c,
                    Duration__c = ( dt.getTime() - wrapper.ttRecord.Activity_Time__c ) * 0.001,
                    DocumentId__c = strDocumentId,
                    Opening_Action__c = 'New Case',
                    Source__c = 'Lightning Component'
                   );
        strJsonTimeTracker = TimeTrackerComponentController.insertTimeTracker( JSON.serialize( ttRecord ) );
        wrapper = ( TimeTrackerComponentWrapper ) JSON.deserialize( strJsonTimeTracker, TimeTrackerComponentWrapper.class );
        System.assertEquals( TRUE, wrapper.isSucceeded );
        
        Test.stopTest();

        System.assertNotEquals( 0, [ SELECT COUNT() FROM Time_Tracker__c 
                                     WHERE DocumentId__c =: strDocumentId 
                                     AND 
                                     Duration__c != NULL 
                                   ] 
                              );
    }
}