Time Tracker Packaging Org/src/objects/Time_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Activity_Time__c</fullName>
        <externalId>true</externalId>
        <label>Activity Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DocumentId__c</fullName>
        <externalId>true</externalId>
        <label>Document Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Tracked Duration</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_Record_Document_Id__c</fullName>
        <label>New Record Document Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <externalId>true</externalId>
        <label>Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opening_Action__c</fullName>
        <label>Opening Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Change Status</fullName>
                </value>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
                <value>
                    <fullName>Edit</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Escalate to L3</fullName>
                </value>
                <value>
                    <fullName>File</fullName>
                </value>
                <value>
                    <fullName>File Upload</fullName>
                </value>
                <value>
                    <fullName>Log a Call</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>New Event</fullName>
                </value>
                <value>
                    <fullName>Post Case Comment</fullName>
                </value>
                <value>
                    <fullName>Start Chat</fullName>
                </value>
                <value>
                    <fullName>Update Case</fullName>
                </value>
                <value>
                    <fullName>Case Comment Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opening_Activity_Time__c</fullName>
        <externalId>true</externalId>
        <label>Opening Activity Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Object_Id__c</fullName>
        <externalId>true</externalId>
        <label>Parent Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>Console Toolkit</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Time Tracker</label>
    <nameField>
        <displayFormat>TT-{000}</displayFormat>
        <label>Time Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Trackers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TimeTrackerConfigSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Time Tracker Config Settings</label>
</CustomObject>

Time Tracker Packaging Org/src/classes/HiddenTimeTrackerControllerTest.cls
@isTest (SeeAllData = false)
/**
* @description unit test class for HiddenTimeTrackerController.cls
*/
public class HiddenTimeTrackerControllerTest {
     private static final String STANDARD_PROFILE_NAME = 'Standard User';
     private static String caseId;

    static CaseComment caseComment;
    static Account acc;
    static Contact con;
	static Case caseObj;
    static opportunity oppObj;
	static User usr= [SELECT Id, LastName FROM User WHERE Id=: UserInfo.getUserId()];
	static DateTime dtNow = Datetime.now();
    private static void init()
	{
		// method to install only new TimeTrackerConfigSettings records
		TimeTrackerTestHelper.insertRecordsFromStaticResource(TimeTrackerUtility.getNamespace()
			+ 'TimeTrackerConfigSettings__c',
			'TimeTrackerConfigSettings_Records');
		System.assertNotEquals(0, TimeTrackerConfigSettings__c.getAll().values().size());
		
		acc = new Account(Name = 'Account Test Name');
		caseObj = new Case(Type = 'Other', Status = 'New', Origin = 'Phone');
        oppObj = new opportunity(StageName= 'Qualification', CloseDate = Date.today(), Name	= 'Test opportunity' );
        con = new Contact(LastName = 'Test Lastname');
		insert acc;
        insert con;
		insert caseObj;
        insert oppObj;
        caseComment = new CaseComment(ParentId = caseObj.Id, CommentBody = 'Test Body');
        insert caseComment; 
        System.assert(acc.Id != null && caseObj.id != null);
	}    
     /**
     * This method sets up the TimeTrackerStrategy custom setting data
     * @param the user  to be used for the Case and Timesheet
     * @return void
     */
    private static void setupData(User usrt) {
        Database.SaveResult sr = null;

         //create a Case record
        Case newCase = new Case(OwnerId = usrt.Id);

        //insert the Case record
        sr = Database.Insert(newCase, true);
        // ensure the Case record has an Id
        system.assertNotEquals(null, sr.getId());
        caseId = sr.getId();
    }

   @isTest static void testInsertActivity() {
        User stdUsr = TimeTrackerTestHelper.createUser(STANDARD_PROFILE_NAME);

        system.runAs(stdUsr) {
            //setupData(stdUsr);
			init();
            
        Time_Tracker__c tt = new Time_Tracker__c(Duration__c= 50, Object_Id__c = caseObj.Id, Source__c = 'Console Toolkit',
                Parent_Object_Id__c= caseObj.Id, Action__c='Case Review', Opening_Action__c = 'Case Review', Opening_Activity_Time__c = 1469099914781L, Activity_Time__c =1469099946909L);
		tt.DocumentId__c = caseObj.Id;
        String jtt = JSON.serialize(tt);
        HiddenTimeTrackerController.insertTimeTracker(jtt);

        Time_Tracker__c updt = new Time_Tracker__c(Duration__c= 50, Object_Id__c = caseObj.Id, Source__c = 'Console Toolkit',
                Parent_Object_Id__c= caseObj.Id, Action__c='Case Review', Opening_Action__c = 'Case Review', Opening_Activity_Time__c = 1469099914781L, Activity_Time__c =1469099946909L);
		updt.DocumentId__c = caseObj.Id;
    	updt.New_Record_Document_Id__c = ''+caseObj.Id;
        String updtjson = JSON.serialize(updt);       
		
       	HiddenTimeTrackerController.insertTimeTracker(updtjson);
       
		tt = new Time_Tracker__c(Duration__c= 50, Object_Id__c = caseComment.Id, Source__c = 'Extension', Action__c='Case Comment Save', Opening_Action__c = 'New Case Comment', Opening_Activity_Time__c = 1469099914781L, Activity_Time__c =1469099946909L);
		tt.DocumentId__c = caseObj.Id;
    	tt.New_Record_Document_Id__c = ''+caseObj.Id;
        updtjson = JSON.serialize(tt);  
       
       HiddenTimeTrackerController.insertTimeTracker(updtjson);
            HiddenTimeTrackerController.getSettings('dummy');
        }
    }

    private static void makeJsonObject(JSONGenerator gen, String objType, Id usrId, String action, 
                                              String actionCategory, String cId, Boolean isTimeTrackerLog) {
        gen.writeStartObject();
        gen.writeStringField('objectType', objType);
        gen.writeStringField('activityDate', String.valueOf((DateTime.now()).getTime()));
        gen.writeStringField('clientId', 'a6c13953-21ea-4271-8499-7b988c158400');
        gen.writeStringField('source', TimeTrackerConstants.SYSTEM_STR);
        gen.writeStringField('user', usrId);
        if(isTimeTrackerLog) {
            gen.writeStringField('level', 'i');
            gen.writeFieldName('log');
            gen.writeStartArray();
            gen.writeStartObject();
            gen.writeStringField('message', 'Error');
            gen.writeStringField('url', '');
            gen.writeEndObject();
            gen.writeEndArray();
        } else {
            gen.writeStringField('action', action);
            gen.writeStringField('actionCategory', actionCategory);
            gen.writeStringField('caseId', cId);
        }
        gen.writeEndObject();
    }
}