src/objects/TimeTrackerConfigSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Time Tracker Config Settings</label>
</CustomObject>

src/objects/TimeTrackerUserSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Weekly_Hours__c</fullName>
        <label>Weekly Hours</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Time Tracker User Settings</label>
</CustomObject>

Time Tracker Packaging Org/src/classes/TimeTrackerPostInstallTest.cls
@isTest( SeeAllData = FALSE )
/**
* @description test class for TimeTrackerPostInstall.cls
*/
public class TimeTrackerPostInstallTest {
    
    private static testMethod void testConfigSettingInstallation()
    {
        Test.startTest();
        
        Test.testInstall( new TimeTrackerPostInstall(), null );
        List<TimeTrackerConfigSettings__c> configSettings = TimeTrackerConfigSettings__c.getAll().values();
        System.assertNotEquals(0, configSettings.size(), ' ; List : ' + configSettings);
        
        Test.testInstall( new TimeTrackerPostInstall(), null );
        
        List<TimeTrackerConfigSettings__c> configSettings2 = TimeTrackerConfigSettings__c.getAll().values();
        
        Test.stopTest();
        
        System.assertEquals( configSettings.size(), configSettings2.size(), '; List : ' + configSettings2 );
        System.assertEquals( 40, TimeTrackerUserSettings__c.getOrgDefaults().Weekly_Hours__c );
    }
}