Time Tracker Developer Org/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Tracked_Duration__c</fullName>
        <label>Tracked Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

Time Tracker Developer Org/src/objects/Time_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Tracked Duration</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <externalId>true</externalId>
        <label>Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Object_Id__c</fullName>
        <externalId>true</externalId>
        <label>Parent Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timesheet_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Entry</label>
        <referenceTo>Timesheet_Entry__c</referenceTo>
        <relationshipLabel>Time Trackers</relationshipLabel>
        <relationshipName>Time_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Timesheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet</label>
        <referenceTo>Timesheet__c</referenceTo>
        <relationshipLabel>Time Trackers</relationshipLabel>
        <relationshipName>Time_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Tracker</label>
    <nameField>
        <displayFormat>TT-{000}</displayFormat>
        <label>Time Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Trackers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Time Tracker Developer Org/src/objects/Timesheet__c.object
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <label>Timesheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Time Tracker Developer Org/src/objects/Timesheet_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <formula>VALUE(LEFT(Time_Spent__c, 2)) * 3600 +

VALUE(

LEFT(
RIGHT(Time_Spent__c,
           LEN(Time_Spent__c) - FIND(&apos;:&apos;, Time_Spent__c)),
   FIND(&apos;:&apos;, 
      RIGHT(Time_Spent__c,
           LEN(Time_Spent__c) - FIND(&apos;:&apos;, Time_Spent__c)
           )
       )
   - 1
    )
) * 60 +

VALUE(RIGHT(Time_Spent__c, 2))</formula>
        <inlineHelpText>@00:00</inlineHelpText>
        <label>Duration (Seconds)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Timesheet__c</fullName>
        <label>Timesheet</label>
        <referenceTo>Timesheet__c</referenceTo>
        <relationshipLabel>Timesheet Entries</relationshipLabel>
        <relationshipName>Timesheet_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Tracked_Duration__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Tracked Duration (Seconds)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Timesheet Entry</label>
    <nameField>
        <displayFormat>TE-{0}</displayFormat>
        <label>Timesheet Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Time Tracker Developer Org/src/objects/TimeTrackerConfigSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Text3__c</fullName>
        <label>Text 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Time Tracker Config Settings</label>
</CustomObject>

Time Tracker Developer Org/src/classes/TimeTrackerRollupUtil_Test.cls
/**
* @description unit test class for TimeTrackerRollupUtil.cls
* @created 09/02/15
*/
@isTest
private class TimeTrackerRollupUtil_Test {
    static Datetime dtNow = Datetime.now();
    
    @isTest static void testRollup() {

        Database.SaveResult sr = null;
        TimeTrackerTestHelper.insertRecordsFromStaticResource(TimeTrackerUtility.getNamespace()
                + 'TimeTrackerConfigSettings__c', 'TimeTrackerConfigSettings_Records');

        try {

            // create test user
            User usr = TimeTrackerTestHelper.createUser();
            Case caseObj = new Case(Type = 'Other', Status = 'New', Origin = 'Phone');
            insert caseObj;

            system.runAs(usr) {
                Integer rand = Crypto.getRandomInteger();
                rand = (rand < 0 ? rand * -1 : rand);
                String randomId = String.valueOf(rand);

                Test.startTest();
                    for(Integer i = 0; i < 2; i++)
                    {
                        // create TimeTracker records
                        Time_Tracker__c caseCreationStart = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.NEW_CASE_STR, String.valueOf(dtNow.addMinutes(1).getTime()), String.valueOf(dtNow.addMinutes(1).getTime()),
                                                                                    '', '', '',
                                                                                    caseObj.Id, caseObj.Id,  
                                                                                    null, usr.Id);
                        insert caseCreationStart;
                        system.assert(caseCreationStart.Id != null);

                        Time_Tracker__c caseCreationend = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.NEW_CASE_STR + ' Save', String.valueOf(dtNow.addMinutes(5).getTime()), String.valueOf(dtNow.addMinutes(5).getTime()),
                                                                                    TimeTrackerConstants.NEW_CASE_STR,String.valueOf(dtNow.addMinutes(1).getTime()) , String.valueOf(dtNow.addMinutes(1).getTime()),
                                                                                    caseObj.Id, caseObj.Id,  
                                                                                    null, usr.Id);
                        caseCreationend.Parent_Object_Id__c = caseObj.Id;

                        // This will execute GenericTimeTrackerImpl
                        insert caseCreationend;
                        system.assert(caseCreationend.Id != null);
                    }
                Test.stopTest();

                List<Timesheet_Entry__c> tseList = [ Select  Id, Name, Timesheet__c, Tracked_Duration__c
                                                    From Timesheet_Entry__c
                                                    Limit 10];
                System.debug(LoggingLevel.ERROR, '--++--tseList : ' + tseList);
                System.assert(!tseList.isEmpty());
                System.assertEquals(1, tseList.size());
                System.assertEquals(480, tseList[0].Tracked_Duration__c, tseList[0].Tracked_Duration__c);
            }
        } catch(Exception ex) {
            system.debug(LoggingLevel.ERROR, 'Exception in running unit test TimeTrackerRollupUtil_Test. Error is: ' + ex.getMessage());
        }
    }

    @isTest static void testRollup_2() {

        Database.SaveResult sr = null;
        TimeTrackerTestHelper.insertRecordsFromStaticResource(TimeTrackerUtility.getNamespace()
                + 'TimeTrackerConfigSettings__c', 'TimeTrackerConfigSettings_Records');

        try {

            // create test user
            User usr = TimeTrackerTestHelper.createUser();
            Case caseObj = new Case(Type = 'Other', Status = 'New', Origin = 'Phone');
            insert caseObj;

            TimeTrackerConfigSettings__c conSet = TimeTrackerConfigSettings__c.getValues('Strategy_New_Case');
            System.assertNotEquals(null, conSet);
            conSet.Text3__c = TimeTrackerConstants.CASE_REVIEW_STR;
            update conSet;

            system.runAs(usr) {
                Integer rand = Crypto.getRandomInteger();
                rand = (rand < 0 ? rand * -1 : rand);
                String randomId = String.valueOf(rand);

                Test.startTest();
                    // delete / comment createNewTimesheetEntry & createNewTimeTracker methods from utility create

                    // create TimeTracker records
                    Time_Tracker__c caseCreationStart = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.NEW_CASE_STR, String.valueOf(dtNow.addMinutes(1).getTime()), String.valueOf(dtNow.addMinutes(1).getTime()),
                                                                                '', '', '',
                                                                                caseObj.Id, caseObj.Id,  
                                                                                null, usr.Id);
                    insert caseCreationStart;
                    system.assert(caseCreationStart.Id != null);

                    Time_Tracker__c caseCreationend = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.NEW_CASE_STR + ' Save', String.valueOf(dtNow.addMinutes(3).getTime()), String.valueOf(dtNow.addMinutes(3).getTime()),
                                                                                TimeTrackerConstants.NEW_CASE_STR,String.valueOf(dtNow.addMinutes(1).getTime()) , String.valueOf(dtNow.addMinutes(1).getTime()),
                                                                                caseObj.Id, caseObj.Id,  
                                                                                null, usr.Id);
                    caseCreationend.Parent_Object_Id__c = caseObj.Id;
                    // This will execute GenericTimeTrackerImpl
                    insert caseCreationend;
                    system.assert(caseCreationend.Id != null);

                    Time_Tracker__c reviewtt = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.CASE_REVIEW_STR, String.valueOf(dtNow.addMinutes(10).getTime()), String.valueOf(dtNow.addMinutes(10).getTime()),
                                                                                TimeTrackerConstants.CASE_REVIEW_STR, String.valueOf(dtNow.getTime()), String.valueOf(dtNow.getTime()),
                                                                                caseObj.Id, '',  
                                                                                null, usr.Id);
                    reviewtt.Object_Id__c = caseObj.Id;
                    reviewtt.Duration__c = 600;
                    reviewtt.Parent_Object_Id__c = caseObj.Id;
                    // This will execute GenericExcludeImpl
                    insert reviewtt;
                    System.assert(reviewtt.Id != null);
                Test.stopTest();

                List<Timesheet_Entry__c> tseList = [ Select  Id, Name, Timesheet__c, Tracked_Duration__c
                                                    From Timesheet_Entry__c
                                                    Limit 10];
                System.debug(LoggingLevel.ERROR, '--++--tseList : ' + tseList);
                System.assert(!tseList.isEmpty());
                System.assertEquals(1, tseList.size());
                System.assertEquals(600, tseList[0].Tracked_Duration__c, tseList[0].Tracked_Duration__c);
            }
        } catch(Exception ex) {
            system.debug(LoggingLevel.ERROR, 'Exception in running unit test TimeTrackerRollupUtil_Test. Error is: ' + ex.getMessage());
        }
    }
}