Time Tracker Developer Org/src/objects/Config_Settings_Table_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>API_Name__c</fullName>
        <description>Holds the API name of the field of Config Custom Settings.</description>
        <inlineHelpText>API name of the field of Config Custom Settings.</inlineHelpText>
        <label>API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkbox_Field__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Holds TRUE if the field type is Checkbox, otherwise, FALSE</description>
        <inlineHelpText>Mark this if the field type is Checkbox.</inlineHelpText>
        <label>Checkbox Field?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Column_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Holds the Order of the Column; needs to be unique within the type of Custom Settings.</description>
        <inlineHelpText>Column Sequence Number</inlineHelpText>
        <label>Column Number</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Holds the Description of the column of Custom Settings Table.</description>
        <inlineHelpText>State the purpose or description of the Column of Custom Settings Table.</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Display__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Holds TRUE if the field is to be displayed, otherwise, FALSE.</description>
        <inlineHelpText>Mark this if this needs to be displayed.</inlineHelpText>
        <label>Display?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>Holds the Label of the column of Custom Settings Table.</description>
        <inlineHelpText>Column Name of Custom Settings Table.</inlineHelpText>
        <label>Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Used__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Holds TRUE if the field is used, otherwise, FALSE</description>
        <inlineHelpText>Mark this field if it is used.</inlineHelpText>
        <label>Used?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <description>Holds the width of the Column</description>
        <inlineHelpText>The width of the Column in &quot;rem&quot;.</inlineHelpText>
        <label>Width</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Config Settings Table Configuration</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>CSTC Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Config Settings Table Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Time Tracker Developer Org/src/classes/ConfigSettingsDTO.cls
/**
    @ Purpose : Wraps the data of the Config Settings Table Configuration.
//*/

public class ConfigSettingsDTO {
    
    public String apiName;
    
    public String labelName;
    
    public String description;
    
    public Boolean isBoolean;
    
    public String width;
    
    public Boolean used;
    
    public Boolean display;
    
    public Integer displayOrder;
    
    public ConfigSettingsDTO() {
        
        this.apiName = '';
        this.labelName = '';
        this.description = '';
        this.isBoolean = FALSE;
        this.width = '';
        this.used = FALSE;
        this.display = FALSE;
        this.displayOrder = 0;
    }
    
    public ConfigSettingsDTO( Config_Settings_Table_Configuration__c ObjConfig ) {
        
        this();
        if( ObjConfig != NULL ) {
            this.apiName = ObjConfig.API_Name__c;
            this.labelName = ObjConfig.Label__c;
            this.description = ObjConfig.Description__c;
            this.isBoolean = ObjConfig.Checkbox_Field__c;
            this.width = ObjConfig.Width__c;
            this.used = ObjConfig.Used__c;
            this.display = ObjConfig.Display__c;
            this.displayOrder = ( Integer ) ObjConfig.Column_Number__c;
        }
    } 
}