Time Tracker Developer Org/src/objects/ManualLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Disengage_Time__c</fullName>
        <label>Disengage Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Duration in seconds when the timer was engaged</description>
        <formula>(Disengage_Time__c -  Engage_Time__c) * 86400</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration (Seconds)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Engage_Time__c</fullName>
        <label>Engage Time</label>
        <type>DateTime</type>
    </fields>
    <label>Manual Line Item</label>
    <nameField>
        <displayFormat>M-{00000000}</displayFormat>
        <label>MLN Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Time Tracker Developer Org/src/objects/Time_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>DocumentId__c</fullName>
        <externalId>true</externalId>
        <label>Document Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Tracked Duration</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opening_Action__c</fullName>
        <label>Opening Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Change Status</fullName>
                </value>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
                <value>
                    <fullName>Edit</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Escalate to L3</fullName>
                </value>
                <value>
                    <fullName>File</fullName>
                </value>
                <value>
                    <fullName>File Upload</fullName>
                </value>
                <value>
                    <fullName>Log a Call</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>New Event</fullName>
                </value>
                <value>
                    <fullName>Post Case Comment</fullName>
                </value>
                <value>
                    <fullName>Start Chat</fullName>
                </value>
                <value>
                    <fullName>Update Case</fullName>
                </value>
                <value>
                    <fullName>Case Comment Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timesheet_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Entry</label>
        <referenceTo>Timesheet_Entry__c</referenceTo>
        <relationshipLabel>Time Trackers</relationshipLabel>
        <relationshipName>Time_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Timesheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet</label>
        <referenceTo>Timesheet__c</referenceTo>
        <relationshipLabel>Time Trackers</relationshipLabel>
        <relationshipName>Time_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Tracker</label>
    <nameField>
        <displayFormat>TT-{000}</displayFormat>
        <label>Time Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Trackers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Time Tracker Developer Org/src/objects/Timesheet__c.object
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <label>Timesheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Time Tracker Developer Org/src/objects/Timesheet_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <formula>VALUE(LEFT(Time_Spent__c, 2)) * 3600 +

VALUE(

LEFT(
RIGHT(Time_Spent__c,
           LEN(Time_Spent__c) - FIND(&apos;:&apos;, Time_Spent__c)),
   FIND(&apos;:&apos;, 
      RIGHT(Time_Spent__c,
           LEN(Time_Spent__c) - FIND(&apos;:&apos;, Time_Spent__c)
           )
       )
   - 1
    )
) * 60 +

VALUE(RIGHT(Time_Spent__c, 2))</formula>
        <inlineHelpText>@00:00</inlineHelpText>
        <label>Duration (Seconds)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Timesheet__c</fullName>
        <label>Timesheet</label>
        <referenceTo>Timesheet__c</referenceTo>
        <relationshipLabel>Timesheet Entries</relationshipLabel>
        <relationshipName>Timesheet_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Timesheet Entry</label>
    <nameField>
        <displayFormat>TE-{0}</displayFormat>
        <label>Timesheet Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Time Tracker Developer Org/src/objects/TimeTrackerConfigSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Time Tracker Config Settings</label>
</CustomObject>

Time Tracker Developer Org/src/classes/ManualLineItemTriggerTest.cls
@isTest(SeeAllData=false)
private class ManualLineItemTriggerTest {
  private static List<Time_Tracker__c> startEventList {get; set;}
  private static List<Time_Tracker__c> endEventList {get; set;}
  private static List<ManualLineItem__c> mItems {get; set;}
  private static String caseId;
  private static String tseId;
  private static DateTime dtNow = Datetime.now();
  private static User usr= [SELECT Id, LastName FROM User WHERE Id=: UserInfo.getUserId()];

  private static void setup()
    {
        //Config-setting
        TimeTrackerTestHelper.insertRecordsFromStaticResource(TimeTrackerUtility.getNamespace()+'TimeTrackerConfigSettings__c', 'TimeTrackerConfigSettings_Records');
        System.assertNotEquals(0, TimeTrackerConfigSettings__c.getAll().size());
        
        //TimeTrackerTestHelper.createTimeStrategyRecords();
        Database.SaveResult sr = null;
        //create a Case record
        Case newCase = new Case(OwnerId = usr.Id);
        //insert the Case record
        sr = Database.Insert(newCase, true);
        caseId = sr.getId();

        // create Timesheet record
        Timesheet__c timesheet = TimeTrackerUtility.createNewTimesheet(system.today(), usr.Id, usr.LastName);
        // insert the Timesheet record
        sr = Database.insert(timesheet, true);

        // create Timesheet Entry record
        Timesheet_Entry__c tse = TimeTrackerUtility.createNewTimesheetEntry(
          TimeTrackerConstants.CASE_CREATION_STR, system.today()
          , TimeTrackerConstants.TIME_SPENT_DEFAULT_VALUE
          , sr.getId(), UserInfo.getUserId());
        // insert the Timesheet Entry record
        sr = Database.insert(tse, true);
        tseId = sr.getId();
    }

  private static void insertManualLineItem1(){
    /*
    ManualLineItem__c mli1 = new ManualLineItem__c(
      Engage_Time__c = dtNow.addMinutes(80)
      , Disengage_Time__c = dtNow.addMinutes(150));
    */
    ManualLineItem__c mli1 = new ManualLineItem__c(
      Engage_Time__c = dtNow.addMinutes(5)
      , Disengage_Time__c = dtNow.addMinutes(12));
    insert mli1;
  }

  private static void insertManualLineItem2(){
    /*
    ManualLineItem__c mli1 = new ManualLineItem__c(
      Engage_Time__c = dtNow.addMinutes(170)
      , Disengage_Time__c = dtNow.addMinutes(190));    
    */
    ManualLineItem__c mli1 = new ManualLineItem__c(
      Engage_Time__c = dtNow.addMinutes(20)
      , Disengage_Time__c = dtNow.addMinutes(25));
    insert mli1;
  }

 @isTest static void Test_excludeManualLineItemTime_Evt0() {
    setup();
    //createTimeTrackerRecords();
    List<Time_Tracker__c> ttList = new List<Time_Tracker__c>();

    /*
    Time_Tracker__c startEvt = TimeTrackerUtility.createNewTimeTracker(
      String.valueOf(dtNow.getTime()), null,
      TimeTrackerConstants.CHATTER_TEXT_POST, TimeTrackerConstants.CASE_WORK_STR,
      caseId, '0', null, 'Event0', TimeTrackerConstants.SYSTEM_STR, tseId, usr.Id);    
    */
    Time_Tracker__c startEvt = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.CHATTER_TEXT_POST, String.valueOf(dtNow.getTime()), String.valueOf(dtNow.getTime()),
                                                                    '','','',
                                                                    caseId, caseId,  
                                                                    null, usr.Id);
    insert startEvt;

    /*
    Time_Tracker__c endEvt = TimeTrackerUtility.createNewTimeTracker(
      String.valueOf(dtNow.addMinutes(10).getTime()), null,
      TimeTrackerConstants.CHATTER_TEXT_POST_STP, TimeTrackerConstants.CASE_WORK_STR,
      caseId, '0', TimeTrackerConstants.CHATTER_TEXT_POST, 'Event0', TimeTrackerConstants.SYSTEM_STR, tseId, usr.Id);    
    */
    Time_Tracker__c endEvt = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.CHATTER_TEXT_POST_STP, String.valueOf(dtNow.addMinutes(1).getTime()), String.valueOf(dtNow.addMinutes(1).getTime()),
                                                                  TimeTrackerConstants.CHATTER_TEXT_POST, String.valueOf(dtNow.getTime()), String.valueOf(dtNow.getTime()),
                                                                  caseId, caseId,  
                                                                  null, usr.Id);
    insert endEvt;

    Test.startTest();
      insertManualLineItem1();
      insertManualLineItem2();
    Test.stopTest();

    Time_Tracker__c event = [SELECT Duration__c FROM Time_Tracker__c WHERE DocumentId__c = :caseId and Opening_Action__c != null];
    system.assertEquals(60, event.Duration__c);
  }

  @isTest static void Test_excludeManualLineItemTime_Evt1() {
    setup();
    List<Time_Tracker__c> ttList = new List<Time_Tracker__c>();

    /*Time_Tracker__c startEvt = TimeTrackerUtility.createNewTimeTracker(
      String.valueOf(dtNow.addMinutes(75).getTime()), null,
      TimeTrackerConstants.CHATTER_TEXT_POST, TimeTrackerConstants.CASE_WORK_STR,
      caseId, '1', null, 'Event1', TimeTrackerConstants.SYSTEM_STR, tseId, usr.Id);*/


    Time_Tracker__c startEvt = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.CHATTER_TEXT_POST, String.valueOf(dtNow.addMinutes(2).getTime()), String.valueOf(dtNow.addMinutes(2).getTime()),
                                                                    '','','',
                                                                    caseId, caseId,  
                                                                    null, usr.Id);
    insert startEvt;

    Time_Tracker__c endEvt = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.CHATTER_TEXT_POST_STP, String.valueOf(dtNow.addMinutes(32).getTime()), String.valueOf(dtNow.addMinutes(32).getTime()),
                                                                  TimeTrackerConstants.CHATTER_TEXT_POST, String.valueOf(dtNow.addMinutes(2).getTime()), String.valueOf(dtNow.addMinutes(2).getTime()),
                                                                  caseId, caseId,  
                                                                  null, usr.Id);

    /*Time_Tracker__c endEvt = TimeTrackerUtility.createNewTimeTracker(
      String.valueOf(dtNow.addMinutes(195).getTime()), null,
      TimeTrackerConstants.CHATTER_TEXT_POST_STP, TimeTrackerConstants.CASE_WORK_STR,
      caseId, '1', TimeTrackerConstants.CHATTER_TEXT_POST, 'Event1', TimeTrackerConstants.SYSTEM_STR, tseId, usr.Id);*/

      insertManualLineItem1();
      insertManualLineItem2();
  
    Test.startTest();
      /*ttList.add(endEvt);
      Database.insert(ttList);*/
      insert endEvt;
    Test.stopTest();

    Time_Tracker__c event = [SELECT Duration__c FROM Time_Tracker__c WHERE DocumentId__c = : caseId and Opening_Action__c != null];
    system.assertEquals(1080, event.Duration__c);
  } 

   @isTest static void Test_excludeManualLineItemTime_Evt2() {
    setup();
    List<Time_Tracker__c> ttList = new List<Time_Tracker__c>();

    /*Time_Tracker__c startEvt = TimeTrackerUtility.createNewTimeTracker(
      String.valueOf(dtNow.addMinutes(70).getTime()), null,
      TimeTrackerConstants.CHATTER_TEXT_POST, TimeTrackerConstants.CASE_WORK_STR,
      caseId, '2', null, 'Event2', TimeTrackerConstants.SYSTEM_STR, tseId, usr.Id);*/

    Time_Tracker__c startEvt = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.CHATTER_TEXT_POST, String.valueOf(dtNow.addMinutes(3).getTime()), String.valueOf(dtNow.addMinutes(3).getTime()),
                                                                    '','','',
                                                                    caseId, caseId,  
                                                                    null, usr.Id);
    insert startEvt;

    /*Time_Tracker__c endEvt = TimeTrackerUtility.createNewTimeTracker(
      String.valueOf(dtNow.addMinutes(90).getTime()), null,
      TimeTrackerConstants.CHATTER_TEXT_POST_STP, TimeTrackerConstants.CASE_WORK_STR,
      caseId, '2', TimeTrackerConstants.CHATTER_TEXT_POST, 'Event2', TimeTrackerConstants.SYSTEM_STR, tseId, usr.Id);*/

    Time_Tracker__c endEvt = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.CHATTER_TEXT_POST_STP, String.valueOf(dtNow.addMinutes(6).getTime()), String.valueOf(dtNow.addMinutes(6).getTime()),
                                                                  TimeTrackerConstants.CHATTER_TEXT_POST, String.valueOf(dtNow.addMinutes(3).getTime()), String.valueOf(dtNow.addMinutes(3).getTime()),
                                                                  caseId, caseId,  
                                                                  null, usr.Id);



    Test.startTest();

      insert endEvt;

      insertManualLineItem1();
      insertManualLineItem2();
    Test.stopTest();

    Time_Tracker__c event = [SELECT Duration__c FROM Time_Tracker__c WHERE DocumentId__c = : caseId and Opening_Action__c != null];
    system.assertEquals(120, event.Duration__c);
  }

  @isTest static void Test_excludeManualLineItemTime_Evt3() {
    setup();
    List<Time_Tracker__c> ttList = new List<Time_Tracker__c>();

    /*Time_Tracker__c startEvt = TimeTrackerUtility.createNewTimeTracker(
      String.valueOf(dtNow.addMinutes(100).getTime()), null,
      TimeTrackerConstants.CHATTER_TEXT_POST, TimeTrackerConstants.CASE_WORK_STR,
      caseId, '3', null, 'Event3', TimeTrackerConstants.SYSTEM_STR, tseId, usr.Id);*/

    Time_Tracker__c startEvt = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.CHATTER_TEXT_POST, String.valueOf(dtNow.addMinutes(7).getTime()), String.valueOf(dtNow.addMinutes(7).getTime()),
                                                                    '','','',
                                                                    caseId, caseId,  
                                                                    null, usr.Id);
    insert startEvt;

    /*Time_Tracker__c endEvt = TimeTrackerUtility.createNewTimeTracker(
      String.valueOf(dtNow.addMinutes(110).getTime()), null,
      TimeTrackerConstants.CHATTER_TEXT_POST_STP, TimeTrackerConstants.CASE_WORK_STR,
      caseId, '3', TimeTrackerConstants.CHATTER_TEXT_POST, 'Event3', TimeTrackerConstants.SYSTEM_STR, tseId, usr.Id);*/

    Time_Tracker__c endEvt = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.CHATTER_TEXT_POST_STP, String.valueOf(dtNow.addMinutes(8).getTime()), String.valueOf(dtNow.addMinutes(8).getTime()),
                                                                  TimeTrackerConstants.CHATTER_TEXT_POST, String.valueOf(dtNow.addMinutes(7).getTime()), String.valueOf(dtNow.addMinutes(7).getTime()),
                                                                  caseId, caseId,  
                                                                  null, usr.Id);


    Test.startTest();
      insert endEvt;

      insertManualLineItem1();
      insertManualLineItem2();
    Test.stopTest();

    Time_Tracker__c event = [SELECT Duration__c FROM Time_Tracker__c WHERE DocumentId__c = : caseId and Opening_Action__c != null];
    system.assertEquals(0, event.Duration__c);
  }

  @isTest static void Test_excludeManualLineItemTime_Evt4() {
    setup();
    List<Time_Tracker__c> ttList = new List<Time_Tracker__c>();

     /*Time_Tracker__c startEvt = TimeTrackerUtility.createNewTimeTracker(
      String.valueOf(dtNow.addMinutes(120).getTime()), null,
      TimeTrackerConstants.CHATTER_TEXT_POST, TimeTrackerConstants.CASE_WORK_STR,
      caseId, '4', null, 'Event4', TimeTrackerConstants.SYSTEM_STR, tseId, usr.Id);*/

    Time_Tracker__c startEvt = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.CHATTER_TEXT_POST, String.valueOf(dtNow.addMinutes(9).getTime()), String.valueOf(dtNow.addMinutes(9).getTime()),
                                                                    '','','',
                                                                    caseId, caseId,  
                                                                    null, usr.Id);
    insert startEvt;      

    /*Time_Tracker__c endEvt = TimeTrackerUtility.createNewTimeTracker(
      String.valueOf(dtNow.addMinutes(200).getTime()), null,
      TimeTrackerConstants.CHATTER_TEXT_POST_STP, TimeTrackerConstants.CASE_WORK_STR,
      caseId, '4', TimeTrackerConstants.CHATTER_TEXT_POST, 'Event4', TimeTrackerConstants.SYSTEM_STR, tseId, usr.Id);*/

    Time_Tracker__c endEvt = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.CHATTER_TEXT_POST_STP, String.valueOf(dtNow.addMinutes(26).getTime()), String.valueOf(dtNow.addMinutes(26).getTime()),
                                                                  TimeTrackerConstants.CHATTER_TEXT_POST, String.valueOf(dtNow.addMinutes(9).getTime()), String.valueOf(dtNow.addMinutes(9).getTime()),
                                                                  caseId, caseId,  
                                                                  null, usr.Id);

    insertManualLineItem1();
    insertManualLineItem2();

    Test.startTest();
      insert endEvt;
    Test.stopTest();

    Time_Tracker__c event = [SELECT Duration__c FROM Time_Tracker__c WHERE DocumentId__c = : caseId and Opening_Action__c != null];
    system.assertEquals(540, event.Duration__c);
  }

  @isTest static void Test_excludeManualLineItemTime_Evt5() {
    setup();
    List<Time_Tracker__c> ttList = new List<Time_Tracker__c>();

    /*Time_Tracker__c startEvt = TimeTrackerUtility.createNewTimeTracker(
      String.valueOf(dtNow.addMinutes(130).getTime()), null,
      TimeTrackerConstants.CHATTER_TEXT_POST, TimeTrackerConstants.CASE_WORK_STR,
      caseId, '5', null, 'Event5', TimeTrackerConstants.SYSTEM_STR, tseId, usr.Id);*/

    Time_Tracker__c startEvt = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.CHATTER_TEXT_POST, String.valueOf(dtNow.addMinutes(10).getTime()), String.valueOf(dtNow.addMinutes(10).getTime()),
                                                                    '','','',
                                                                    caseId, caseId,  
                                                                    null, usr.Id);
    insert startEvt; 

    /*Time_Tracker__c endEvt = TimeTrackerUtility.createNewTimeTracker(
      String.valueOf(dtNow.addMinutes(180).getTime()), null,
      TimeTrackerConstants.CHATTER_TEXT_POST_STP, TimeTrackerConstants.CASE_WORK_STR,
      caseId, '5', TimeTrackerConstants.CHATTER_TEXT_POST, 'Event5', TimeTrackerConstants.SYSTEM_STR, tseId, usr.Id);*/

    Time_Tracker__c endEvt = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.CHATTER_TEXT_POST_STP, String.valueOf(dtNow.addMinutes(21).getTime()), String.valueOf(dtNow.addMinutes(21).getTime()),
                                                                  TimeTrackerConstants.CHATTER_TEXT_POST, String.valueOf(dtNow.addMinutes(10).getTime()), String.valueOf(dtNow.addMinutes(10).getTime()),
                                                                  caseId, caseId,  
                                                                  null, usr.Id);


    Test.startTest();
      insertManualLineItem1();

      insert endEvt;

      insertManualLineItem2();
    Test.stopTest();

    Time_Tracker__c event = [SELECT Duration__c FROM Time_Tracker__c WHERE DocumentId__c = : caseId and Opening_Action__c != null];
    system.assertEquals(480, event.Duration__c);
  }

  @isTest static void Test_excludeManualLineItemTime_Evt6() {
    setup();
    List<Time_Tracker__c> ttList = new List<Time_Tracker__c>();

    /*Time_Tracker__c startEvt = TimeTrackerUtility.createNewTimeTracker(
      String.valueOf(dtNow.addMinutes(140).getTime()), null,
      TimeTrackerConstants.CHATTER_TEXT_POST, TimeTrackerConstants.CASE_WORK_STR,
      caseId, '6', null, 'Event6', TimeTrackerConstants.SYSTEM_STR, tseId, usr.Id);*/

    Time_Tracker__c startEvt = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.CHATTER_TEXT_POST, String.valueOf(dtNow.addMinutes(11).getTime()), String.valueOf(dtNow.addMinutes(11).getTime()),
                                                                    '','','',
                                                                    caseId, caseId,  
                                                                    null, usr.Id);
    insert startEvt;

    /*Time_Tracker__c endEvt = TimeTrackerUtility.createNewTimeTracker(
      String.valueOf(dtNow.addMinutes(160).getTime()), null,
      TimeTrackerConstants.CHATTER_TEXT_POST_STP, TimeTrackerConstants.CASE_WORK_STR,
      caseId, '6', TimeTrackerConstants.CHATTER_TEXT_POST, 'Event6', TimeTrackerConstants.SYSTEM_STR, tseId, usr.Id);*/

    Time_Tracker__c endEvt = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.CHATTER_TEXT_POST_STP, String.valueOf(dtNow.addMinutes(15).getTime()), String.valueOf(dtNow.addMinutes(15).getTime()),
                                                                  TimeTrackerConstants.CHATTER_TEXT_POST, String.valueOf(dtNow.addMinutes(11).getTime()), String.valueOf(dtNow.addMinutes(11).getTime()),
                                                                  caseId, caseId,  
                                                                  null, usr.Id);

    Test.startTest();
      insertManualLineItem1();

      insert endEvt;

      insertManualLineItem2();
    Test.stopTest();

    Time_Tracker__c event = [SELECT Duration__c FROM Time_Tracker__c WHERE DocumentId__c =: caseId and Opening_Action__c != null];
    system.assertEquals(180, event.Duration__c);
  }

  @isTest static void Test_excludeManualLineItemTime_Evt7() {
    setup();
    List<Time_Tracker__c> ttList = new List<Time_Tracker__c>();

    /*Time_Tracker__c startEvt = TimeTrackerUtility.createNewTimeTracker(
      String.valueOf(dtNow.addMinutes(220).getTime()), null,
      TimeTrackerConstants.CHATTER_TEXT_POST, TimeTrackerConstants.CASE_WORK_STR,
      caseId, '7', null, 'Event7', TimeTrackerConstants.SYSTEM_STR, tseId, usr.Id);*/

    Time_Tracker__c startEvt = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.CHATTER_TEXT_POST, String.valueOf(dtNow.addMinutes(27).getTime()), String.valueOf(dtNow.addMinutes(27).getTime()),
                                                                    '','','',
                                                                    caseId, caseId,  
                                                                    null, usr.Id);
    insert startEvt;

    /*Time_Tracker__c endEvt = TimeTrackerUtility.createNewTimeTracker(
      String.valueOf(dtNow.addMinutes(230).getTime()), null,
      TimeTrackerConstants.CHATTER_TEXT_POST_STP, TimeTrackerConstants.CASE_WORK_STR,
      caseId, '7', TimeTrackerConstants.CHATTER_TEXT_POST, 'Event7', TimeTrackerConstants.SYSTEM_STR, tseId, usr.Id);*/

    Time_Tracker__c endEvt = TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.CHATTER_TEXT_POST_STP, String.valueOf(dtNow.addMinutes(29).getTime()), String.valueOf(dtNow.addMinutes(29).getTime()),
                                                                  TimeTrackerConstants.CHATTER_TEXT_POST, String.valueOf(dtNow.addMinutes(27).getTime()), String.valueOf(dtNow.addMinutes(27).getTime()),
                                                                  caseId, caseId,  
                                                                  null, usr.Id);

    insertManualLineItem1();
    insertManualLineItem2();

    Test.startTest();
      insert endEvt;
    Test.stopTest();

    Time_Tracker__c event = [SELECT Duration__c FROM Time_Tracker__c WHERE DocumentId__c = :caseId and Opening_Action__c != null];
    system.assertEquals(120, event.Duration__c);
  }
}