Time Tracker Developer Org/src/objects/ManualLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Disengage_Time__c</fullName>
        <label>Disengage Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Duration in seconds when the timer was engaged</description>
        <formula>(Disengage_Time__c -  Engage_Time__c) * 86400</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration (Seconds)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Engage_Time__c</fullName>
        <label>Engage Time</label>
        <type>DateTime</type>
    </fields>
    <label>Manual Line Item</label>
    <nameField>
        <displayFormat>M-{00000000}</displayFormat>
        <label>MLN Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Time Tracker Developer Org/src/objects/Time_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Action_Category__c</fullName>
        <label>Action Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Case Work</fullName>
                </value>
                <value>
                    <fullName>Non-Case Work</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Housekeeping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Action_Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Action Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <label>Activity Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Activity_Time__c</fullName>
        <externalId>true</externalId>
        <label>Activity Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Tracked Duration</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsBillable__c</fullName>
        <defaultValue>true</defaultValue>
        <description>States whether activity is counted as Billable or Non-Billable. Defaulted as Checked (Automated activities). For Manual activities its value will depend on settings in &apos;TimeTracker Manual Activities&apos; custom-settings.</description>
        <label>IsBillable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsUtilized__c</fullName>
        <defaultValue>true</defaultValue>
        <description>States whether activity is counted as Utilized or Non-Utilized. Defaulted as Checked (Automated activities). For Manual activities its value will depend on settings in &apos;TimeTracker Manual Activities&apos; custom-settings.</description>
        <label>IsUtilized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Non_Reportable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non-Reportable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <externalId>true</externalId>
        <label>Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opening_Action__c</fullName>
        <label>Opening Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Change Status</fullName>
                </value>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
                <value>
                    <fullName>Edit</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Escalate to L3</fullName>
                </value>
                <value>
                    <fullName>File</fullName>
                </value>
                <value>
                    <fullName>File Upload</fullName>
                </value>
                <value>
                    <fullName>Log a Call</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>New Event</fullName>
                </value>
                <value>
                    <fullName>Post Case Comment</fullName>
                </value>
                <value>
                    <fullName>Start Chat</fullName>
                </value>
                <value>
                    <fullName>Update Case</fullName>
                </value>
                <value>
                    <fullName>Case Comment Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>Console Toolkit</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_Spent__c</fullName>
        <defaultValue>&apos;00:00:00&apos;</defaultValue>
        <label>Time Spent (HH:MM:SS)</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timesheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet</label>
        <referenceTo>Timesheet__c</referenceTo>
        <relationshipLabel>Time Trackers</relationshipLabel>
        <relationshipName>Time_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Tracker</label>
    <nameField>
        <displayFormat>TT-{000}</displayFormat>
        <label>Time Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Trackers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Time Tracker Developer Org/src/objects/Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <label>Timesheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Time Tracker Developer Org/src/objects/TimeTrackerConfigSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Code1__c</fullName>
        <description>Manual- Case or Account Link
Strategy- Implementation class Name</description>
        <label>Code 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code2__c</fullName>
        <label>Code 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flag1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Flag 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Flag 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Flag 3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Text3__c</fullName>
        <label>Text 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Time Tracker Config Settings</label>
</CustomObject>

Time Tracker Developer Org/src/classes/ManualWidgetHelper.cls
public with sharing class ManualWidgetHelper {
	public static string  activityLst;
  	public static set<String> activity_actType_map = new set<String>();
  
	public static string getactivityLst(String dummy){
	    TimeTrackerUtility.addLogMessage(LoggingLevel.INFO, 'Started TimeTrackerController.getactivityLst() method.',
	    Datetime.now(), null, null, null, UserInfo.getUserId());
	    activityLst = '';
	    activity_actType_map = TimeTrackerConfigSettings.getManualSettings().keySet();
	    List<String> ttlst = new List<String>(activity_actType_map);
	    ttlst.sort();
	    if(activity_actType_map != null && !activity_actType_map.isEmpty()) {
	    	for(String activity: ttlst) {
	        	activityLst = activityLst + activity + ',';
	      	}
	    }
	    System.debug( 'activityLst:-\n' + JSON.serialize( activityLst ) );
	    return activityLst;
  	}
    
    public static String doCreateTimesheetEntry(String timer, String hiddenTimer, String activityDateStr, String activity,
	String sObjetId, String sObjectValue, String comment)
	{
		System.debug('***doCreateTimesheetEntry > ');
        System.debug('***timer > '+timer);
        System.debug('***hiddenTimer > '+hiddenTimer);
        System.debug('***activityDateStr > '+activityDateStr);
        System.debug('***activity > '+activity);
        System.debug('***sObjetId > '+sObjetId);
        System.debug('***sObjectValue > '+sObjectValue);
        System.debug('***comment > '+ comment);
	    TimeTrackerUtility.addLogMessage(LoggingLevel.INFO, 'Started TimeTrackerController.doCreateTimesheetEntry() method.',
	    Datetime.now(), null, null, null, UserInfo.getUserId());
	    TimeTrackerUtility.addLogMessage(LoggingLevel.DEBUG, '@@ timer::'+timer+' hiddenTimer::'+hiddenTimer+' activityDateStr::'+ activityDateStr+' activity::'+activity
	    +' sObjetId::'+sObjetId+' sObjectValue::'+sObjectValue+' comment::'+comment,
	    Datetime.now(), null, null, null, UserInfo.getUserId());
	
	    String retVal = TimeTrackerConstants.FALSE_TEXT;
	    try
	    {
		      TimeTrackerConfigSettings__c activityDetails  = TimeTrackerConfigSettings.getactivityvsActivityDetails().get(activity);
		      TimeTrackerUtility.addLogMessage(LoggingLevel.INFO, 'Activity Details Returned for Activity: '+ activity + '::'+ activityDetails,
		      Datetime.now(), null, null, null, UserInfo.getUserId());
		      TimeTrackerUtility.addLogMessage(LoggingLevel.DEBUG, 'Activity Datetime: '+ activityDateStr,
		      Datetime.now(), null, null, null, UserInfo.getUserId());
		
		      String actionCategory = activityDetails.Text3__c;
		      if(String.isBlank(activityDateStr)) { return TimeTrackerConstants.ERROR_OCCURRED_TEXT; }
		      Datetime activityDate = TimeTrackerLocaleToDateFormat.convertStringToDate(activityDateStr);
		      
		      Time_Tracker__c tt = new Time_Tracker__c();
		      tt.Action__c = activity;
		      tt.Opening_Action__c = activity;
		      tt.Action_Category__c = actionCategory;
		      tt.Source__c = TimeTrackerConstants.MANUAL_STR;
		      tt.Action_Closed__c = true;
		      tt.User__c = UserInfo.getUserId();
		      tt.Duration__c = (String.isNotBlank(hiddenTimer)) ? Integer.valueOf(hiddenTimer) : 0;
		      tt.Time_Spent__c = String.isNotBlank(timer) ? timer : '';
		      tt.Activity_Time__c = activityDate.getTime();
		      tt.Activity_Date__c = activityDate;
		      tt.Comment__c = String.isNotBlank(comment) && (comment.length() > 255) ? comment.substring(0, 254) : comment;
		
		      //Values from Custom-settings
		      tt.IsBillable__c = activityDetails.Flag1__c;
		      tt.IsUtilized__c = activityDetails.Flag2__c;
		      tt.Non_Reportable__c = activityDetails.Flag3__c;
		      System.debug('TT : '+tt);
		      //Validate sObject using code2 and code1 fields from manual custom settings
		      sObject typeAheadObjectCheck = getSObjectDetailsFromActivityAndSObjectValue(activity, sObjectValue);
		      if(String.isNotBlank(sObjectValue)){
		        if(typeAheadObjectCheck==null) {
		            tt.Object_Id__c = sObjetId;
		            return System.Label.ERR_Invalid_SObject; 
		        } else tt.Object_Id__c = typeAheadObjectCheck.Id;
		      }
		      System.debug('typeAheadObjectCheck : '+typeAheadObjectCheck);
		      TimeTrackerUtility.addLogMessage(LoggingLevel.INFO, 'Manual Activity TimeTracker record to be inserted ::' + tt,
		      Datetime.now(), null, null, null, UserInfo.getUserId());
		        
		      Database.SaveResult sr = Database.insert(tt, false);
		      System.debug('sr : '+sr);
		      if(sr.isSuccess()) {
		        retVal = TimeTrackerConstants.TRUE_TEXT;
		        //Check whether timesheet for current week is locked
		        String timesheet = getTimesheetId(sr.getId());
		        if(String.isBlank(timesheet)) retVal = TimeTrackerConstants.LOCKED_TEXT;
		      } else {
		        if(String.valueOf(sr.getErrors()).contains(TimeTrackerConstants.ERROR_TIMESHEET_LOCKED)) 
		            retVal = TimeTrackerConstants.LOCKED_TEXT;
		        else{
		            TimeTrackerUtility.addLogMessage(LoggingLevel.ERROR, String.valueOf(sr.getErrors()),
		            Datetime.now(), null, null, null, UserInfo.getUserId());
		            retVal = TimeTrackerConstants.FALSE_TEXT;
		        }
		      }
	    } catch(Exception ex) {
	      retVal = TimeTrackerConstants.FALSE_TEXT;
	      TimeTrackerUtility.addLogMessage(LoggingLevel.ERROR, TimeTrackerUtility.createExceptionLogString(ex),
	      Datetime.now(), null, null, null, UserInfo.getUserId());
	    } finally {
	      TimeTrackerUtility.upsertLogRecord();
	    }
	
	    TimeTrackerUtility.addLogMessage(LoggingLevel.INFO, 'Ended TimeTrackerController.doCreateTimesheetEntry() method.',
	    Datetime.now(), null, null, null, UserInfo.getUserId());
	    TimeTrackerUtility.addLogMessage(LoggingLevel.DEBUG, 'Returned: retVal: ' + retVal,
	    Datetime.now(), null, null, null, UserInfo.getUserId());
	    
	    return retVal;
	}
	
	private static sObject getSObjectDetailsFromActivityAndSObjectValue(String activity, String sObjectValue) {
	    TimeTrackerUtility.addLogMessage(LoggingLevel.INFO, 'Started TimeTrackerController.getSObjectDetailsFromActivityAndSObjectValue() method.',
	    Datetime.now(), null, null, null, UserInfo.getUserId());
	    TimeTrackerUtility.addLogMessage(LoggingLevel.DEBUG, 'activity: ' + activity +', sObjectValue : '+sObjectValue,
	    Datetime.now(), null, null, null, UserInfo.getUserId());
	    
	    sObject sObjectRecord ;
	    if(String.isBlank(activity) || String.isBlank(sObjectValue)) return sObjectRecord;
	    TimeTrackerConfigSettings__c  currentManualSettings = new TimeTrackerConfigSettings__c();
	    currentManualSettings = TimeTrackerConfigSettings.getManualSettings().get(activity);
	    String code2Fields = currentManualSettings.Code2__c;
	    String sObjectApiName = currentManualSettings.Code1__c;
	    String sObjectSearchField = '';
	    if(sObjectApiName.contains('*')) {
	        sObjectApiName = sObjectApiName.substring(0,sObjectApiName.length()-1);
	    }
	    System.debug('code2Fields : '+code2Fields+', '+'sObjectApiName:'+sObjectApiName);
	    Map<String, Object> fieldList = (Map<String, Object>)JSON.deserializeUntyped(code2Fields.replace(';',','));
	    System.debug('fieldList : '+fieldList);
	    // to be implement filter logic
	    List<Object> lstFieldObject = (List<Object>)fieldList.get('fields');
	    for(Object eachField :lstFieldObject) {
	        Map<String,Object> eachParsedField = (Map<String,Object>)eachField;
	        if((Boolean)eachParsedField.get('search')) {
	            sObjectSearchField = (String)eachParsedField.get('field');
	            break;
	        }
	        System.debug('Code2 Field Details:: field : '+eachParsedField.get('field')+', search: '+eachParsedField.get('search')+', show: '+eachParsedField.get('show'));
	    }
	    System.debug('sObjectApiName : '+sObjectApiName+'sObjectSearchField : '+sObjectSearchField+'sObjectValue:'+sObjectValue);
	    sObjectRecord = getSObjectIdFromValue(sObjectApiName, sObjectSearchField, sObjectValue);
	    
	    TimeTrackerUtility.addLogMessage(LoggingLevel.INFO, 'Ended TimeTrackerController.getSObjectDetailsFromActivityAndSObjectValue() method.',
	    Datetime.now(), null, null, null, UserInfo.getUserId());
	    TimeTrackerUtility.addLogMessage(LoggingLevel.DEBUG, 'sObjectRecord: ' + sObjectRecord,
	    Datetime.now(), null, null, null, UserInfo.getUserId());
	    return sObjectRecord;
    }
    
    private static String getTimesheetId(String ttId) {
	    String timesheetId='';
	    if(String.isBlank(ttId)) return timesheetId;
	    Time_Tracker__c tt = [ SELECT Timesheet__c FROM Time_Tracker__c WHERE Id=:ttId ];
	    timesheetId = tt.Timesheet__c;
	    return timesheetId;
	}
	
	private static sObject getSObjectIdFromValue(String sObjectName, String searchField, String sObjectValue) {
	    String soqlString='';
	    sObject sObjectObj;
	    List<sObject> sObjectObjList;
	    
	    if(String.isBlank(sObjectName) || String.isBlank(searchField) || String.isBlank(sObjectValue)) return sObjectObj;
	    
	    try {
	        sObjectValue = sObjectValue.trim();
	        // to be implement for multiple show fields
	        soqlString = ' SELECT Id FROM '+sObjectName+' WHERE '+ searchField + ' = \'' + sObjectValue+'\'';
	        //System.debug('###########soqlString'+soqlString);
	        sObjectObjList = Database.query(soqlString);
	    } catch(QueryException ex) {
	        System.debug('Exception ex : '+ex);
	        TimeTrackerUtility.addLogMessage(LoggingLevel.DEBUG, 'Exception in TrackerController.getSObjectFieldsFromId() method, SOQL String : '+soqlString+', QueryException : ' + ex,
	        Datetime.now(), null, null, null, UserInfo.getUserId());
	    }
	    //System.debug('###########sObjectObj'+sObjectObjList[0]);
	    if(sObjectObjList!=null && !sObjectObjList.isEmpty())
	      sObjectObj = sObjectObjList[0];
	
	    return sObjectObj;
	}
	
	public static List<ManualLineItem__c> saveManualLineItems(String data){
    //system.debug('@@saveManualLineItems'+ data);
    TimeTrackerUtility.addLogMessage(LoggingLevel.INFO, 'Started TimeTrackerController.saveManualLineItems() method.',
    Datetime.now(), null, null, null, UserInfo.getUserId());
    TimeTrackerUtility.addLogMessage(LoggingLevel.DEBUG, 'data: ' + data,
    Datetime.now(), null, null, null, UserInfo.getUserId());
    List<ManualLineItem__c> manualLineItems = new List<ManualLineItem__c>();
    try {
      for(Object obj : (List<Object>) JSON.deserializeUntyped(data)) {
        Map<String, Object> objMap = (Map<String, Object>) obj;
        ManualLineItem__c mli = new ManualLineItem__c();
        mli.Engage_Time__c = objMap.containsKey('Engage_Time__c') ? TimeTrackerUtility.convertDate(String.valueOf(objMap.get('Engage_Time__c'))) : null;
        mli.Disengage_Time__c = objMap.containsKey('Disengage_Time__c') ? TimeTrackerUtility.convertDate(String.valueOf(objMap.get('Disengage_Time__c'))) : null;
        manualLineItems.add(mli);
      }
      //System.debug('manualLineItems  :  '+manualLineItems);
      insert manualLineItems;
    } catch(Exception e) {
      TimeTrackerUtility.addLogMessage(LoggingLevel.ERROR, TimeTrackerUtility.createExceptionLogString(e),
      Datetime.now(), null, null, null, UserInfo.getUserId());
    }
    TimeTrackerUtility.addLogMessage(LoggingLevel.INFO, 'End of TimeTrackerController.saveManualLineItems() method.',
    Datetime.now(), null, null, null, UserInfo.getUserId());
    TimeTrackerUtility.addLogMessage(LoggingLevel.DEBUG, 'Returned: manualLineItems: ' + manualLineItems,
    Datetime.now(), null, null, null, UserInfo.getUserId());
    return manualLineItems;
  }
}