Time Tracker Developer Org/src/objects/Time_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Object_Id__c</fullName>
        <externalId>true</externalId>
        <label>Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timesheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet</label>
        <referenceTo>Timesheet__c</referenceTo>
        <relationshipLabel>Time Trackers</relationshipLabel>
        <relationshipName>Time_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Tracker</label>
    <nameField>
        <displayFormat>TT-{000}</displayFormat>
        <label>Time Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Trackers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Time Tracker Developer Org/src/objects/Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <label>Timesheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Time Tracker Developer Org/src/objects/TimeTracker_StagingLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Name__c</fullName>
        <label>Activity Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <externalId>true</externalId>
        <label>Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TimeTracker_Associated__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TimeTracker Associated</label>
        <referenceTo>Time_Tracker__c</referenceTo>
        <relationshipLabel>TimeTracker Staging Line Items</relationshipLabel>
        <relationshipName>TimeTracker_Staging_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TimeTracker Staging Line Item</label>
    <nameField>
        <displayFormat>TSLI-{00000000}</displayFormat>
        <label>Time Tracker Staging Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TimeTracker Staging Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Time Tracker Developer Org/src/classes/TimeTrackerStagingLineItem.cls
/**
 * @description a class implementing Batchable to create time tracker records
 *
 */
global class TimeTrackerStagingLineItem implements Database.Batchable<sObject> {
    Set<Id> errorIds;
    global final String query;
    global static List<TimeTracker_StagingLineItem__c> stagingLineItems;

   /**
   * @description constructor used to set the query string
   *
   */
	global TimeTrackerStagingLineItem() {
		String namespacePrefix = TimeTrackerUtility.getNamespace();
        query = 'SELECT Id, Name, OwnerId,'
        		+ namespacePrefix + 'Activity_Name__c, '
        		+ namespacePrefix + 'End_Date__c, '
        		+ namespacePrefix + 'Object_Id__c, '
        		+ namespacePrefix + 'Object_Name__c, '
        		+ namespacePrefix + 'Start_Date__c, '
                + namespacePrefix + 'TimeTracker_Associated__c '
        		+ 'FROM ' + namespacePrefix + 'TimeTracker_StagingLineItem__c '
                + 'WHERE CreatedDate  > YESTERDAY '
                + 'ORDER BY Start_Date__c ';
        TimeTrackerUtility.addLogMessage(LoggingLevel.DEBUG, 'TimeTrackerStagingLineItem: query: ' + query,
            Datetime.now(), null, null, null, UserInfo.getUserId());
	}

    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope)
    {
        Map<Id, Timesheet__c> tsToUnlock = new Map<Id, Timesheet__c>();
    	try{

            stagingLineItems = (List<TimeTracker_StagingLineItem__c>) scope;
            TimeTrackerUtility.addLogMessage(LoggingLevel.INFO, 'Staging Scope-records' + stagingLineItems,
                Datetime.now(), null, null, null, UserInfo.getUserId());

            if(stagingLineItems!=null){

                //Check if timesheet for any user is submitted if yes change status temporary so we can 
                tsToUnlock = TimeTrackerStagingLineItemHelper.getLockedTimesheetsOfStagingUser(stagingLineItems);
                if(tsToUnlock!= null && !tsToUnlock.isEmpty()) {
                    Boolean result = TimeTrackerStagingLineItemHelper.temporaryChangeStatusOfLockedTimesheets(tsToUnlock.keySet());
                    if(!result) { return; }
                }
                //System.debug('tsToUnlock : '+tsToUnlock);

                //Get list of TimeTracker records to be inserted
                Map<Id,Time_Tracker__c> ttRecordsToUpsert = TimeTrackerStagingLineItemHelper.getTimeTrackersInsertList(stagingLineItems);

                //Insert TimeTracker records
                List<Database.UpsertResult> resultList = Database.upsert(ttRecordsToUpsert.values(), false);
                for(Database.UpsertResult result : resultList) {
                    if(!result.isSuccess()){
                        errorIds = new Set<Id>();
                        errorIds.add(result.getId());
                        //get IDs of the errorneous records
                        TimeTrackerUtility.addLogMessage(LoggingLevel.DEBUG, 'Error while Inserting Time-Tracker-records ' + result.getErrors(),
                                Datetime.now(), null, null, null, UserInfo.getUserId());
                    }
                }
                //Delete Staging-records
                Delete stagingLineItems;
                TimeTrackerUtility.addLogMessage(LoggingLevel.DEBUG, 'Staging records deleted',
                                                 Datetime.now(), null, null, null, UserInfo.getUserId());
            }

            TimeTrackerUtility.addLogMessage(LoggingLevel.INFO, 'End of TimeTrackerStagingLineItem.execute method.',
                Datetime.now(), null, null, null, UserInfo.getUserId());
    	} catch(Exception ex) {
            TimeTrackerUtility.addLogMessage(LoggingLevel.ERROR, TimeTrackerUtility.createExceptionLogString(ex),
                Datetime.now(), null, null, null, UserInfo.getUserId());
        } finally {
            //re-assign original status to timsheet
            if(tsToUnlock!= null && !tsToUnlock.isEmpty()) {
                Boolean result = TimeTrackerStagingLineItemHelper.reassignOriginalStatusForLockedTimesheet(tsToUnlock);
            }
            TimeTrackerUtility.upsertLogRecord();
        }
    }

    global void finish(Database.BatchableContext BC){
    }
}