Time Tracker Developer Org/src/objects/Time_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opening_Action__c</fullName>
        <label>Opening Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Change Status</fullName>
                </value>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
                <value>
                    <fullName>Edit</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Escalate to L3</fullName>
                </value>
                <value>
                    <fullName>File</fullName>
                </value>
                <value>
                    <fullName>File Upload</fullName>
                </value>
                <value>
                    <fullName>Log a Call</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>New Event</fullName>
                </value>
                <value>
                    <fullName>Post Case Comment</fullName>
                </value>
                <value>
                    <fullName>Start Chat</fullName>
                </value>
                <value>
                    <fullName>Update Case</fullName>
                </value>
                <value>
                    <fullName>Case Comment Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>Console Toolkit</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_Spent__c</fullName>
        <defaultValue>&apos;00:00:00&apos;</defaultValue>
        <label>Time Spent (HH:MM:SS)</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Time Tracker</label>
    <nameField>
        <displayFormat>TT-{000}</displayFormat>
        <label>Time Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Trackers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Time Tracker Developer Org/src/objects/TimeTrackerUserSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Is_Time_Tracker_Read_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Time Tracker Read Only</label>
        <type>Checkbox</type>
    </fields>
    <label>Time Tracker User Settings</label>
</CustomObject>

Time Tracker Developer Org/src/classes/TimeTrackerUpdateController.cls
public class TimeTrackerUpdateController {

    private final Time_Tracker__c ttRec;
    public static Boolean isTimeSpentReadOnly{ get;set; }
    
    public List<SelectOption> activities{ get;set; }
    
    //public static Map<String,String> activity_actType_map = new Map<String,String>();
    set<String> activity_actType_map = new set<String>();
    
    public TimeTrackerUpdateController() {
        
    }
    
    public TimeTrackerUpdateController( ApexPages.StandardController controller ) {
        
        TimeTrackerUtility.addLogMessage(LoggingLevel.INFO, 'Initialting TimeTrackerUpdateController.TimeTrackerUpdateController constructor.',
            Datetime.now(), null, null, null, UserInfo.getUserId());
        TimeTrackerUtility.addLogMessage(LoggingLevel.DEBUG, 'controller: ' + controller,
            Datetime.now(), null, null, null, UserInfo.getUserId());
        
        if( !Test.isRunningTest() ) {
            Controller.addFields(new List<String>{'Source__c'});
        }
        
        this.ttRec = (Time_Tracker__c)Controller.getRecord();
        System.debug(LoggingLevel.ERROR, '--++--ttRec : ' + ttRec);
        if( ttRec.Source__c != 'Manual' ) {
           ApexPages.Message errTimeTrackerEdit = new ApexPages.Message(ApexPages.Severity.INFO, System.Label.Err_TimeTracker_Edit);
           ApexPages.addMessage(errTimeTrackerEdit);
            //return;
        }
        System.debug('UserInfo.getUserId() : '+UserInfo.getUserId());
        isTimeSpentReadOnly = getIsTimeSpentReadOnlyDetails(UserInfo.getUserId(), UserInfo.getProfileId());
        if(isTimeSpentReadOnly){
            ApexPages.Message errTimeTrackerEdit = new ApexPages.Message(ApexPages.Severity.INFO, System.Label.ERR_Not_Authorize_to_Edit_Time_Tracker);
            ApexPages.addMessage(errTimeTrackerEdit);
        }
        activity_actType_map = TimeTrackerConfigSettings.getManualSettings().keyset();
        TimeTrackerUtility.addLogMessage(LoggingLevel.DEBUG, 'activity_actType_map: ' + activity_actType_map,
            Datetime.now(), null, null, null, UserInfo.getUserId());
            
        List<String> ttlst = new List<String>(activity_actType_map);
        ttlst.sort();
        activities = new List<SelectOption>();
        
        if(ttRec.Opening_Action__c != NULL && activity_actType_map != null && !activity_actType_map.isEmpty()) {
            
            //Check if it is Automated-activity to be edited-if yes add it in list
            if( !activity_actType_map.contains((ttRec.Opening_Action__c)) ){

                activities.add(new SelectOption(ttRec.Opening_Action__c,ttRec.Opening_Action__c));

            }
            for(String activity: ttlst) {
                activities.add(new SelectOption(activity,activity));
            }
        }
        TimeTrackerUtility.addLogMessage(LoggingLevel.INFO, 'End of TimeTrackerUpdateController.TimeTrackerUpdateController method.',
            Datetime.now(), null, null, null, UserInfo.getUserId());
    }

    private Boolean getIsTimeSpentReadOnlyDetails( String userId, String profileId ) {
        
        Boolean isTimeSpentReadOnly = false;
        try {
            TimeTrackerUserSettings__c recordUserSetting = TimeTrackerUserSettings__c.getValues( userId );
            System.debug( 'recordUserSetting-By-User-Id:-\n' + JSON.serialize( recordUserSetting ) );
            
            if( recordUserSetting == NULL ) {
                recordUserSetting = TimeTrackerUserSettings__c.getInstance( profileId );
                System.debug( 'recordUserSetting-By-Profile-Id:-\n' + JSON.serialize( recordUserSetting ) );
            }
            
            if( recordUserSetting.Is_Time_Tracker_Read_Only__c ) {
                List<PermissionSetAssignment> listPSA = [ SELECT Id, Assignee.Id, PermissionSet.Name 
                                                          FROM PermissionSetAssignment 
                                                          WHERE 
                                                          AssigneeId =: userId 
                                                          AND 
                                                          PermissionSet.Name =: TimeTrackerConstants.TIME_TRACKER_ADMIN_PERMISSION_SET_API_NAME
                                                        ];
                System.debug( 'listPSA:-\n' + JSON.serialize( listPSA ) );
                isTimeSpentReadOnly = listPSA.isEmpty();
            }
        } 
        catch( Exception ex ) {
            TimeTrackerUtility.addLogMessage( LoggingLevel.DEBUG, 
                                              'Exception occured in TimeTrackerUpdateController.getIsTimeSpentReadOnlyDetails method, Details: '+ex,
                                              Datetime.now(), null, null, null, UserInfo.getUserId()
                                            );
        }
        System.debug( 'isTimeSpentReadOnly:-\n' + isTimeSpentReadOnly );
        return isTimeSpentReadOnly;
    }
    
    public PageReference Save(){
        
        TimeTrackerUtility.addLogMessage(LoggingLevel.INFO, 'Started TimeTrackerUpdateController.Save method.',
            Datetime.now(), null, null, null, UserInfo.getUserId());
        try{
            /*
            if(ttRec.Opening_Action__c == TimeTrackerConstants.GENERAL_OTHER && String.isBlank(ttRec.Comment__c) ){
                ApexPages.Message commentReqdError = new ApexPages.Message(ApexPages.Severity.FATAL, System.Label.ERR_Comment_Required);
                ApexPages.addMessage(commentReqdError);
                return null;
            }
            //*/
            System.debug('@@ttRec : '+ttRec);
            if(String.isBlank(ttRec.Time_Spent__c) || !checkTimerFormat(ttRec.Time_Spent__c)){
                ApexPages.Message invalidDuration = new ApexPages.Message(ApexPages.Severity.FATAL, System.Label.ERR_Invalid_duration);
                ApexPages.addMessage(invalidDuration);
                return null;
            }
            update ttRec;
            PageReference pr = new PageReference('/'+ttRec.Id);
            pr.setRedirect(true);
            TimeTrackerUtility.addLogMessage(LoggingLevel.INFO, 'End of TimeTrackerUpdateController.Save method.',
                Datetime.now(), null, null, null, UserInfo.getUserId());
            return pr;
        }catch(Exception e){
             Apexpages.addMessages(e);
             TimeTrackerUtility.addLogMessage(LoggingLevel.ERROR, TimeTrackerUtility.createExceptionLogString(e),
                 Datetime.now(), null, null, null, UserInfo.getUserId());
        }
        finally
        {
            TimeTrackerUtility.upsertLogRecord();
        }
        return null;
    }
    
    private Boolean checkTimerFormat(String timer) {
        
        String timerRegEx = '([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]';
        Pattern MyPattern = Pattern.compile(timerRegEx);
        Matcher MyMatcher = MyPattern.matcher(timer);
        Boolean result = MyMatcher.matches();
        return result;
    }
}