Time Tracker Developer Org/src/objects/Time_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Tracked Duration</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opening_Action__c</fullName>
        <label>Opening Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Change Status</fullName>
                </value>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
                <value>
                    <fullName>Edit</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Escalate to L3</fullName>
                </value>
                <value>
                    <fullName>File</fullName>
                </value>
                <value>
                    <fullName>File Upload</fullName>
                </value>
                <value>
                    <fullName>Log a Call</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>New Event</fullName>
                </value>
                <value>
                    <fullName>Post Case Comment</fullName>
                </value>
                <value>
                    <fullName>Start Chat</fullName>
                </value>
                <value>
                    <fullName>Update Case</fullName>
                </value>
                <value>
                    <fullName>Case Comment Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Time Tracker</label>
    <nameField>
        <displayFormat>TT-{000}</displayFormat>
        <label>Time Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Trackers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Time Tracker Developer Org/src/objects/TimeTrackerConfigSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Time Tracker Config Settings</label>
</CustomObject>

Time Tracker Developer Org/src/objects/TimeTrackerUserSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ClientDebugLevel__c</fullName>
        <label>Client Debug Level</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Time_Tracker_Read_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Time Tracker Read Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Duration_In_Minutes__c</fullName>
        <label>Tracking Timeout ( Minutes )</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Server_Debug_Level__c</fullName>
        <description>Sets the debug level for the log records</description>
        <inlineHelpText>Add one of the following values: FINEST, FINER, FINE, DEBUG, INFO, WARN, ERROR</inlineHelpText>
        <label>Server Debug Level</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Server_Debug__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Server Debug</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Weekly_Hours__c</fullName>
        <label>Weekly Hours</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Time Tracker User Settings</label>
</CustomObject>

Time Tracker Developer Org/src/classes/TimeTrackerUpdateController_Test.cls
@isTest (SeeAllData = false)
//Unit-test for TimeTrackerUpdateController
public class TimeTrackerUpdateController_Test {
  private static User usr= [SELECT Id, LastName FROM User WHERE Id=: UserInfo.getUserId()];
  private static String caseId;
  private static Database.SaveResult sr = null;
  private static DateTime dtNow = Datetime.now();

    private static void setup()
    {  
        TimeTrackerUserSettings__c ttUserSettingsInstance = new TimeTrackerUserSettings__c
                            (
                                                     SetUpOwnerId = UserInfo.getProfileId(),
                                                     Is_Time_Tracker_Read_Only__c = TRUE,
                                                     ClientDebugLevel__c = 'INFO',
                                                     Max_Duration_In_Minutes__c = 100,
                                                     Server_Debug__c = TRUE,
                                                     Server_Debug_Level__c = 'INFO',
                                                     Weekly_Hours__c = 40   
                                                    );
    insert ttUserSettingsInstance;
        
    // method to install only new TimeTrackerConfigSettings records
    TimeTrackerTestHelper.insertRecordsFromStaticResource(TimeTrackerUtility.getNamespace()
      + 'TimeTrackerConfigSettings__c',
      'TimeTrackerConfigSettings_Records');
    System.assertNotEquals(0, TimeTrackerConfigSettings__c.getAll().values().size());
        
        //create a Case record
        Case newCase = new Case(OwnerId = usr.Id);
        //insert the Case record
        sr = Database.Insert(newCase, true);
        caseId = sr.getId();   
    }

    @isTest static void testManualTimeTracker() {
  
        setup();
      
        Integer rand = Crypto.getRandomInteger();
        rand = (rand < 0 ? rand * -1 : rand);
        String randomId = String.valueOf(rand);
              
        //Config-setting
        TimeTrackerTestHelper.insertRecordsFromStaticResource('TimeTrackerConfigSettings__c', 'TimeTrackerConfigSettings_Records');      

            
        Time_Tracker__c manualTTRec= TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.CASE_REVIEW_STR, String.valueOf(dtNow.getTime()), String.valueOf(dtNow.getTime()),
                                                                                TimeTrackerConstants.CASE_REVIEW_STR + ' End', String.valueOf(dtNow.addMinutes(-5).getTime()),String.valueOf(dtNow.addMinutes(-5).getTime()),
                                                                                caseId, caseId,  
                                                                                null, usr.Id);
        manualTTRec.Duration__c = 300;
        
        

        // insert the TimeTracker record with start action
        sr = Database.insert(manualTTRec);

        // ensure the TimeTracker record has an Id
        system.assertNotEquals(null, sr.getId());

        Test.startTest();
          PageReference pgRef = Page.TimeTrackerUpdate;
           Test.setCurrentPageReference (pgRef);
          ApexPages.StandardController stdTT = new ApexPages.StandardController(manualTTRec);
           TimeTrackerUpdateController myPgCont = new TimeTrackerUpdateController(stdTT);
          manualTTRec.Action__c = 'Email';
                        
          myPgCont.save();
      
          
        Test.stopTest();
       
        Time_Tracker__c activity = [SELECT Duration__c FROM Time_Tracker__c WHERE Id=: sr.getId()];
        system.assertEquals(300, activity.Duration__c);
    }
    
    @isTest static void testErrorMessage() {
        
        //Test error message when Opening_Action__c is null
       Time_Tracker__c manualTTRec1= TimeTrackerUtility.createTimeTracker(TimeTrackerConstants.GENERAL_OTHER, String.valueOf(dtNow.getTime()), String.valueOf(dtNow.getTime()),
                                                                                TimeTrackerConstants.GENERAL_OTHER, String.valueOf(dtNow.addMinutes(-5).getTime()),String.valueOf(dtNow.addMinutes(-5).getTime()),
                                                                                caseId, caseId,  
                                                                                null, usr.Id);
       manualTTRec1.Duration__c = 20;
       manualTTRec1.Comment__c = 'Hello'; 
        // insert the TimeTracker record with start action
        sr = Database.insert(manualTTRec1);

        // ensure the TimeTracker record has an Id
        system.assertNotEquals(null, sr.getId());

        Test.startTest();
          PageReference pgRef = Page.TimeTrackerUpdate;
           Test.setCurrentPageReference (pgRef);
          ApexPages.StandardController stdTT = new ApexPages.StandardController(manualTTRec1);
           TimeTrackerUpdateController myPgCont = new TimeTrackerUpdateController(stdTT);
          //manualTTRec1.Action__c = 'Email';
          
        System.debug('myPgCont : '+myPgCont);
        System.debug('myPgCont opening action : '+myPgCont);
        
          myPgCont.save();
        ApexPages.Message[] pageMessages = ApexPages.getMessages();
     System.assertNotEquals(0, pageMessages.size());
          
        Test.stopTest();
        
        //Test error message when activity is general other
    } 
}